// src/app.ts
import express from "express";
import cors from "cors";
import dotenv from "dotenv";

// src/router/index.ts
import { Router as Router6 } from "express";

// src/modules/auth/auth.router.ts
import { Router } from "express";

// src/modules/auth/auth.service.ts
import status from "http-status";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// src/generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.6.0",
  "engineVersion": "75cbdc1eb7150937890ad5465d861175c6624711",
  "activeProvider": "postgresql",
  "inlineSchema": 'model User {\n  id            String    @id\n  name          String\n  email         String\n  emailVerified Boolean   @default(false)\n  image         String?\n  role          Role      @default(GUEST)\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n  isDeleted     Boolean   @default(false)\n  deletedAt     DateTime?\n  sessions      Session[]\n  accounts      Account[]\n  bookings      Booking[]\n  reviews       Review[]\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nmodel Booking {\n  id             String        @id @default(uuid(7))\n  userId         String\n  roomId         String\n  checkInDate    DateTime\n  checkOutDate   DateTime\n  totalNights    Int\n  totalPrice     Decimal       @db.Decimal(10, 2) // \u2705 Float \u098F\u09B0 \u09AC\u09A6\u09B2\u09C7 Decimal\n  bookingStatus  BookingStatus @default(PENDING)\n  paymentStatus  PaymentStatus @default(UNPAID)\n  specialRequest String?\n\n  user    User     @relation(fields: [userId], references: [id])\n  room    Room     @relation(fields: [roomId], references: [id])\n  payment Payment?\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([userId])\n  @@index([roomId])\n}\n\nenum Role {\n  ADMIN\n  GUEST\n  MANAGER\n}\n\nenum RoomType {\n  SINGLE\n  DOUBLE\n  DELUXE\n  SUITE\n  FAMILY\n}\n\nenum BedType {\n  SINGLE\n  DOUBLE\n  QUEEN\n  KING\n}\n\nenum RoomStatus {\n  AVAILABLE\n  MAINTENANCE\n}\n\nenum BookingStatus {\n  PENDING\n  CONFIRMED\n  CANCELLED\n  CHECKED_IN\n  CHECKED_OUT\n}\n\nenum PaymentStatus {\n  UNPAID\n  PAID\n  REFUNDED\n  FAILED\n}\n\nenum PaymentMethod {\n  SSLCOMMERZ\n  STRIPE\n  PAYPAL\n}\n\nmodel Payment {\n  id                 String        @id @default(uuid(7))\n  amount             Float\n  transactionId      String        @unique @db.Uuid()\n  stripeEventId      String?       @unique\n  status             PaymentStatus @default(UNPAID)\n  paymentGatewayData Json?\n  createdAt          DateTime      @default(now())\n  updatedAt          DateTime      @updatedAt\n\n  bookingId String  @unique\n  booking   Booking @relation(fields: [bookingId], references: [id], onDelete: Cascade)\n\n  @@index([bookingId])\n  @@index([transactionId])\n  @@map("payments")\n}\n\nmodel Review {\n  id        String   @id @default(uuid(7))\n  userId    String\n  roomId    String\n  rating    Int\n  comment   String?\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n  room      Room     @relation(fields: [roomId], references: [id], onDelete: Cascade)\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([userId])\n  @@index([roomId])\n}\n\nmodel Room {\n  id            String     @id @default(uuid(7))\n  roomNumber    String     @unique\n  roomType      RoomType\n  title         String\n  description   String?\n  pricePerNight Float\n  capacity      Int\n  bedType       BedType\n  images        String\n  status        RoomStatus @default(AVAILABLE)\n  floor         Int?\n  bookings      Booking[]\n  reviews       Review[]\n  createdAt     DateTime   @default(now())\n  updatedAt     DateTime   @updatedAt\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"isDeleted","kind":"scalar","type":"Boolean"},{"name":"deletedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"roomId","kind":"scalar","type":"String"},{"name":"checkInDate","kind":"scalar","type":"DateTime"},{"name":"checkOutDate","kind":"scalar","type":"DateTime"},{"name":"totalNights","kind":"scalar","type":"Int"},{"name":"totalPrice","kind":"scalar","type":"Decimal"},{"name":"bookingStatus","kind":"enum","type":"BookingStatus"},{"name":"paymentStatus","kind":"enum","type":"PaymentStatus"},{"name":"specialRequest","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"BookingToUser"},{"name":"room","kind":"object","type":"Room","relationName":"BookingToRoom"},{"name":"payment","kind":"object","type":"Payment","relationName":"BookingToPayment"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Payment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"amount","kind":"scalar","type":"Float"},{"name":"transactionId","kind":"scalar","type":"String"},{"name":"stripeEventId","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"PaymentStatus"},{"name":"paymentGatewayData","kind":"scalar","type":"Json"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToPayment"}],"dbName":"payments"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"roomId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"room","kind":"object","type":"Room","relationName":"ReviewToRoom"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Room":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"roomNumber","kind":"scalar","type":"String"},{"name":"roomType","kind":"enum","type":"RoomType"},{"name":"title","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"pricePerNight","kind":"scalar","type":"Float"},{"name":"capacity","kind":"scalar","type":"Int"},{"name":"bedType","kind":"enum","type":"BedType"},{"name":"images","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"RoomStatus"},{"name":"floor","kind":"scalar","type":"Int"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToRoom"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToRoom"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","bookings","room","reviews","_count","booking","payment","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","_avg","_sum","Booking.groupBy","Booking.aggregate","Payment.findUnique","Payment.findUniqueOrThrow","Payment.findFirst","Payment.findFirstOrThrow","Payment.findMany","Payment.createOne","Payment.createMany","Payment.createManyAndReturn","Payment.updateOne","Payment.updateMany","Payment.updateManyAndReturn","Payment.upsertOne","Payment.deleteOne","Payment.deleteMany","Payment.groupBy","Payment.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Room.findUnique","Room.findUniqueOrThrow","Room.findFirst","Room.findFirstOrThrow","Room.findMany","Room.createOne","Room.createMany","Room.createManyAndReturn","Room.updateOne","Room.updateMany","Room.updateManyAndReturn","Room.upsertOne","Room.deleteOne","Room.deleteMany","Room.groupBy","Room.aggregate","AND","OR","NOT","id","roomNumber","RoomType","roomType","title","description","pricePerNight","capacity","BedType","bedType","images","RoomStatus","status","floor","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","every","some","none","userId","roomId","rating","comment","amount","transactionId","stripeEventId","PaymentStatus","paymentGatewayData","bookingId","string_contains","string_starts_with","string_ends_with","array_starts_with","array_ends_with","array_contains","checkInDate","checkOutDate","totalNights","totalPrice","BookingStatus","bookingStatus","paymentStatus","specialRequest","identifier","value","expiresAt","accountId","providerId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","name","email","emailVerified","image","Role","role","isDeleted","deletedAt","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "9QNLgAERBAAApQIAIAUAAKYCACAGAAD9AQAgCAAA_gEAIJQBAAChAgAwlQEAAB4AEJYBAAChAgAwlwEBAAAAAaUBQAD8AQAhpgFAAPwBACHcAQEA9AEAId0BAQAAAAHeASAAogIAId8BAQD2AQAh4QEAAKMC4QEi4gEgAKICACHjAUAApAIAIQEAAAABACAMAwAAqgIAIJQBAACxAgAwlQEAAAMAEJYBAACxAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHPAUAA_AEAIdkBAQD0AQAh2gEBAPYBACHbAQEA9gEAIQMDAADKAwAg2gEAALICACDbAQAAsgIAIAwDAACqAgAglAEAALECADCVAQAAAwAQlgEAALECADCXAQEAAAABpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhzwFAAPwBACHZAQEAAAAB2gEBAPYBACHbAQEA9gEAIQMAAAADACABAAAEADACAAAFACARAwAAqgIAIJQBAACwAgAwlQEAAAcAEJYBAACwAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHQAQEA9AEAIdEBAQD0AQAh0gEBAPYBACHTAQEA9gEAIdQBAQD2AQAh1QFAAKQCACHWAUAApAIAIdcBAQD2AQAh2AEBAPYBACEIAwAAygMAINIBAACyAgAg0wEAALICACDUAQAAsgIAINUBAACyAgAg1gEAALICACDXAQAAsgIAINgBAACyAgAgEQMAAKoCACCUAQAAsAIAMJUBAAAHABCWAQAAsAIAMJcBAQAAAAGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHQAQEA9AEAIdEBAQD0AQAh0gEBAPYBACHTAQEA9gEAIdQBAQD2AQAh1QFAAKQCACHWAUAApAIAIdcBAQD2AQAh2AEBAPYBACEDAAAABwAgAQAACAAwAgAACQAgEgMAAKoCACAHAACrAgAgCwAArwIAIJQBAACsAgAwlQEAAAsAEJYBAACsAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACG2AQEA9AEAIcUBQAD8AQAhxgFAAPwBACHHAQIA-AEAIcgBEACtAgAhygEAAK4CygEiywEAAIkCvQEizAEBAPYBACEEAwAAygMAIAcAAMsDACALAADMAwAgzAEAALICACASAwAAqgIAIAcAAKsCACALAACvAgAglAEAAKwCADCVAQAACwAQlgEAAKwCADCXAQEAAAABpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACHFAUAA_AEAIcYBQAD8AQAhxwECAPgBACHIARAArQIAIcoBAACuAsoBIssBAACJAr0BIswBAQD2AQAhAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAALACABAAAMADACAAANACAMAwAAqgIAIAcAAKsCACCUAQAAqQIAMJUBAAAQABCWAQAAqQIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACG3AQIA-AEAIbgBAQD2AQAhAwMAAMoDACAHAADLAwAguAEAALICACAMAwAAqgIAIAcAAKsCACCUAQAAqQIAMJUBAAAQABCWAQAAqQIAMJcBAQAAAAGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACG2AQEA9AEAIbcBAgD4AQAhuAEBAPYBACEDAAAAEAAgAQAAEQAwAgAAEgAgAQAAAAsAIAEAAAAQACANCgAAiwIAIJQBAACIAgAwlQEAABYAEJYBAACIAgAwlwEBAPQBACGjAQAAiQK9ASKlAUAA_AEAIaYBQAD8AQAhuQEIAPcBACG6AQEApwIAIbsBAQD2AQAhvQEAAIoCACC-AQEA9AEAIQEAAAAWACADAAAAEAAgAQAAEQAwAgAAEgAgAQAAAAMAIAEAAAAHACABAAAACwAgAQAAABAAIAEAAAABACARBAAApQIAIAUAAKYCACAGAAD9AQAgCAAA_gEAIJQBAAChAgAwlQEAAB4AEJYBAAChAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAh3AEBAPQBACHdAQEA9AEAId4BIACiAgAh3wEBAPYBACHhAQAAowLhASLiASAAogIAIeMBQACkAgAhBgQAAMgDACAFAADJAwAgBgAA6wIAIAgAAOwCACDfAQAAsgIAIOMBAACyAgAgAwAAAB4AIAEAAB8AMAIAAAEAIAMAAAAeACABAAAfADACAAABACADAAAAHgAgAQAAHwAwAgAAAQAgDgQAAMQDACAFAADFAwAgBgAAxgMAIAgAAMcDACCXAQEAAAABpQFAAAAAAaYBQAAAAAHcAQEAAAAB3QEBAAAAAd4BIAAAAAHfAQEAAAAB4QEAAADhAQLiASAAAAAB4wFAAAAAAQERAAAjACAKlwEBAAAAAaUBQAAAAAGmAUAAAAAB3AEBAAAAAd0BAQAAAAHeASAAAAAB3wEBAAAAAeEBAAAA4QEC4gEgAAAAAeMBQAAAAAEBEQAAJQAwAREAACUAMA4EAACWAwAgBQAAlwMAIAYAAJgDACAIAACZAwAglwEBALgCACGlAUAAwAIAIaYBQADAAgAh3AEBALgCACHdAQEAuAIAId4BIACUAwAh3wEBALoCACHhAQAAlQPhASLiASAAlAMAIeMBQACJAwAhAgAAAAEAIBEAACgAIAqXAQEAuAIAIaUBQADAAgAhpgFAAMACACHcAQEAuAIAId0BAQC4AgAh3gEgAJQDACHfAQEAugIAIeEBAACVA-EBIuIBIACUAwAh4wFAAIkDACECAAAAHgAgEQAAKgAgAgAAAB4AIBEAACoAIAMAAAABACAYAAAjACAZAAAoACABAAAAAQAgAQAAAB4AIAUJAACRAwAgHgAAkwMAIB8AAJIDACDfAQAAsgIAIOMBAACyAgAgDZQBAACaAgAwlQEAADEAEJYBAACaAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAh3AEBANcBACHdAQEA1wEAId4BIACbAgAh3wEBANkBACHhAQAAnALhASLiASAAmwIAIeMBQACWAgAhAwAAAB4AIAEAADAAMB0AADEAIAMAAAAeACABAAAfADACAAABACABAAAABQAgAQAAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAkDAACQAwAglwEBAAAAAaUBQAAAAAGmAUAAAAABtQEBAAAAAc8BQAAAAAHZAQEAAAAB2gEBAAAAAdsBAQAAAAEBEQAAOQAgCJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAHPAUAAAAAB2QEBAAAAAdoBAQAAAAHbAQEAAAABAREAADsAMAERAAA7ADAJAwAAjwMAIJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAhzwFAAMACACHZAQEAuAIAIdoBAQC6AgAh2wEBALoCACECAAAABQAgEQAAPgAgCJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAhzwFAAMACACHZAQEAuAIAIdoBAQC6AgAh2wEBALoCACECAAAAAwAgEQAAQAAgAgAAAAMAIBEAAEAAIAMAAAAFACAYAAA5ACAZAAA-ACABAAAABQAgAQAAAAMAIAUJAACMAwAgHgAAjgMAIB8AAI0DACDaAQAAsgIAINsBAACyAgAgC5QBAACZAgAwlQEAAEcAEJYBAACZAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAhtQEBANcBACHPAUAA3wEAIdkBAQDXAQAh2gEBANkBACHbAQEA2QEAIQMAAAADACABAABGADAdAABHACADAAAAAwAgAQAABAAwAgAABQAgAQAAAAkAIAEAAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACAOAwAAiwMAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAHQAQEAAAAB0QEBAAAAAdIBAQAAAAHTAQEAAAAB1AEBAAAAAdUBQAAAAAHWAUAAAAAB1wEBAAAAAdgBAQAAAAEBEQAATwAgDZcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAHQAQEAAAAB0QEBAAAAAdIBAQAAAAHTAQEAAAAB1AEBAAAAAdUBQAAAAAHWAUAAAAAB1wEBAAAAAdgBAQAAAAEBEQAAUQAwAREAAFEAMA4DAACKAwAglwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACHQAQEAuAIAIdEBAQC4AgAh0gEBALoCACHTAQEAugIAIdQBAQC6AgAh1QFAAIkDACHWAUAAiQMAIdcBAQC6AgAh2AEBALoCACECAAAACQAgEQAAVAAgDZcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAh0AEBALgCACHRAQEAuAIAIdIBAQC6AgAh0wEBALoCACHUAQEAugIAIdUBQACJAwAh1gFAAIkDACHXAQEAugIAIdgBAQC6AgAhAgAAAAcAIBEAAFYAIAIAAAAHACARAABWACADAAAACQAgGAAATwAgGQAAVAAgAQAAAAkAIAEAAAAHACAKCQAAhgMAIB4AAIgDACAfAACHAwAg0gEAALICACDTAQAAsgIAINQBAACyAgAg1QEAALICACDWAQAAsgIAINcBAACyAgAg2AEAALICACAQlAEAAJUCADCVAQAAXQAQlgEAAJUCADCXAQEA1wEAIaUBQADfAQAhpgFAAN8BACG1AQEA1wEAIdABAQDXAQAh0QEBANcBACHSAQEA2QEAIdMBAQDZAQAh1AEBANkBACHVAUAAlgIAIdYBQACWAgAh1wEBANkBACHYAQEA2QEAIQMAAAAHACABAABcADAdAABdACADAAAABwAgAQAACAAwAgAACQAgCZQBAACUAgAwlQEAAGMAEJYBAACUAgAwlwEBAAAAAaUBQAD8AQAhpgFAAPwBACHNAQEA9AEAIc4BAQD0AQAhzwFAAPwBACEBAAAAYAAgAQAAAGAAIAmUAQAAlAIAMJUBAABjABCWAQAAlAIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIc0BAQD0AQAhzgEBAPQBACHPAUAA_AEAIQADAAAAYwAgAQAAZAAwAgAAYAAgAwAAAGMAIAEAAGQAMAIAAGAAIAMAAABjACABAABkADACAABgACAGlwEBAAAAAaUBQAAAAAGmAUAAAAABzQEBAAAAAc4BAQAAAAHPAUAAAAABAREAAGgAIAaXAQEAAAABpQFAAAAAAaYBQAAAAAHNAQEAAAABzgEBAAAAAc8BQAAAAAEBEQAAagAwAREAAGoAMAaXAQEAuAIAIaUBQADAAgAhpgFAAMACACHNAQEAuAIAIc4BAQC4AgAhzwFAAMACACECAAAAYAAgEQAAbQAgBpcBAQC4AgAhpQFAAMACACGmAUAAwAIAIc0BAQC4AgAhzgEBALgCACHPAUAAwAIAIQIAAABjACARAABvACACAAAAYwAgEQAAbwAgAwAAAGAAIBgAAGgAIBkAAG0AIAEAAABgACABAAAAYwAgAwkAAIMDACAeAACFAwAgHwAAhAMAIAmUAQAAkwIAMJUBAAB2ABCWAQAAkwIAMJcBAQDXAQAhpQFAAN8BACGmAUAA3wEAIc0BAQDXAQAhzgEBANcBACHPAUAA3wEAIQMAAABjACABAAB1ADAdAAB2ACADAAAAYwAgAQAAZAAwAgAAYAAgAQAAAA0AIAEAAAANACADAAAACwAgAQAADAAwAgAADQAgAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAALACABAAAMADACAAANACAPAwAA5wIAIAcAAIIDACALAADoAgAglwEBAAAAAaUBQAAAAAGmAUAAAAABtQEBAAAAAbYBAQAAAAHFAUAAAAABxgFAAAAAAccBAgAAAAHIARAAAAABygEAAADKAQLLAQAAAL0BAswBAQAAAAEBEQAAfgAgDJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAG2AQEAAAABxQFAAAAAAcYBQAAAAAHHAQIAAAAByAEQAAAAAcoBAAAAygECywEAAAC9AQLMAQEAAAABAREAAIABADABEQAAgAEAMA8DAADfAgAgBwAAgQMAIAsAAOACACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACG1AQEAuAIAIbYBAQC4AgAhxQFAAMACACHGAUAAwAIAIccBAgC8AgAhyAEQANsCACHKAQAA3ALKASLLAQAA3QK9ASLMAQEAugIAIQIAAAANACARAACDAQAgDJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAhtgEBALgCACHFAUAAwAIAIcYBQADAAgAhxwECALwCACHIARAA2wIAIcoBAADcAsoBIssBAADdAr0BIswBAQC6AgAhAgAAAAsAIBEAAIUBACACAAAACwAgEQAAhQEAIAMAAAANACAYAAB-ACAZAACDAQAgAQAAAA0AIAEAAAALACAGCQAA_AIAIB4AAP8CACAfAAD-AgAgYAAA_QIAIGEAAIADACDMAQAAsgIAIA-UAQAAjAIAMJUBAACMAQAQlgEAAIwCADCXAQEA1wEAIaUBQADfAQAhpgFAAN8BACG1AQEA1wEAIbYBAQDXAQAhxQFAAN8BACHGAUAA3wEAIccBAgDbAQAhyAEQAI0CACHKAQAAjgLKASLLAQAAggK9ASLMAQEA2QEAIQMAAAALACABAACLAQAwHQAAjAEAIAMAAAALACABAAAMADACAAANACANCgAAiwIAIJQBAACIAgAwlQEAABYAEJYBAACIAgAwlwEBAAAAAaMBAACJAr0BIqUBQAD8AQAhpgFAAPwBACG5AQgA9wEAIboBAQAAAAG7AQEAAAABvQEAAIoCACC-AQEAAAABAQAAAI8BACABAAAAjwEAIAMKAAD7AgAguwEAALICACC9AQAAsgIAIAMAAAAWACABAACSAQAwAgAAjwEAIAMAAAAWACABAACSAQAwAgAAjwEAIAMAAAAWACABAACSAQAwAgAAjwEAIAoKAAD6AgAglwEBAAAAAaMBAAAAvQECpQFAAAAAAaYBQAAAAAG5AQgAAAABugEBAAAAAbsBAQAAAAG9AYAAAAABvgEBAAAAAQERAACWAQAgCZcBAQAAAAGjAQAAAL0BAqUBQAAAAAGmAUAAAAABuQEIAAAAAboBAQAAAAG7AQEAAAABvQGAAAAAAb4BAQAAAAEBEQAAmAEAMAERAACYAQAwCgoAAPkCACCXAQEAuAIAIaMBAADdAr0BIqUBQADAAgAhpgFAAMACACG5AQgAuwIAIboBAQC4AgAhuwEBALoCACG9AYAAAAABvgEBALgCACECAAAAjwEAIBEAAJsBACAJlwEBALgCACGjAQAA3QK9ASKlAUAAwAIAIaYBQADAAgAhuQEIALsCACG6AQEAuAIAIbsBAQC6AgAhvQGAAAAAAb4BAQC4AgAhAgAAABYAIBEAAJ0BACACAAAAFgAgEQAAnQEAIAMAAACPAQAgGAAAlgEAIBkAAJsBACABAAAAjwEAIAEAAAAWACAHCQAA9AIAIB4AAPcCACAfAAD2AgAgYAAA9QIAIGEAAPgCACC7AQAAsgIAIL0BAACyAgAgDJQBAACAAgAwlQEAAKQBABCWAQAAgAIAMJcBAQDXAQAhowEAAIICvQEipQFAAN8BACGmAUAA3wEAIbkBCADaAQAhugEBAIECACG7AQEA2QEAIb0BAACDAgAgvgEBANcBACEDAAAAFgAgAQAAowEAMB0AAKQBACADAAAAFgAgAQAAkgEAMAIAAI8BACABAAAAEgAgAQAAABIAIAMAAAAQACABAAARADACAAASACADAAAAEAAgAQAAEQAwAgAAEgAgAwAAABAAIAEAABEAMAIAABIAIAkDAADQAgAgBwAA8wIAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAG2AQEAAAABtwECAAAAAbgBAQAAAAEBEQAArAEAIAeXAQEAAAABpQFAAAAAAaYBQAAAAAG1AQEAAAABtgEBAAAAAbcBAgAAAAG4AQEAAAABAREAAK4BADABEQAArgEAMAkDAADOAgAgBwAA8gIAIJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAhtgEBALgCACG3AQIAvAIAIbgBAQC6AgAhAgAAABIAIBEAALEBACAHlwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACG2AQEAuAIAIbcBAgC8AgAhuAEBALoCACECAAAAEAAgEQAAswEAIAIAAAAQACARAACzAQAgAwAAABIAIBgAAKwBACAZAACxAQAgAQAAABIAIAEAAAAQACAGCQAA7QIAIB4AAPACACAfAADvAgAgYAAA7gIAIGEAAPECACC4AQAAsgIAIAqUAQAA_wEAMJUBAAC6AQAQlgEAAP8BADCXAQEA1wEAIaUBQADfAQAhpgFAAN8BACG1AQEA1wEAIbYBAQDXAQAhtwECANsBACG4AQEA2QEAIQMAAAAQACABAAC5AQAwHQAAugEAIAMAAAAQACABAAARADACAAASACASBgAA_QEAIAgAAP4BACCUAQAA8wEAMJUBAADAAQAQlgEAAPMBADCXAQEAAAABmAEBAAAAAZoBAAD1AZoBIpsBAQD0AQAhnAEBAPYBACGdAQgA9wEAIZ4BAgD4AQAhoAEAAPkBoAEioQEBAPQBACGjAQAA-gGjASKkAQIA-wEAIaUBQAD8AQAhpgFAAPwBACEBAAAAvQEAIAEAAAC9AQAgEgYAAP0BACAIAAD-AQAglAEAAPMBADCVAQAAwAEAEJYBAADzAQAwlwEBAPQBACGYAQEA9AEAIZoBAAD1AZoBIpsBAQD0AQAhnAEBAPYBACGdAQgA9wEAIZ4BAgD4AQAhoAEAAPkBoAEioQEBAPQBACGjAQAA-gGjASKkAQIA-wEAIaUBQAD8AQAhpgFAAPwBACEEBgAA6wIAIAgAAOwCACCcAQAAsgIAIKQBAACyAgAgAwAAAMABACABAADBAQAwAgAAvQEAIAMAAADAAQAgAQAAwQEAMAIAAL0BACADAAAAwAEAIAEAAMEBADACAAC9AQAgDwYAAOkCACAIAADqAgAglwEBAAAAAZgBAQAAAAGaAQAAAJoBApsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BAgAAAAGgAQAAAKABAqEBAQAAAAGjAQAAAKMBAqQBAgAAAAGlAUAAAAABpgFAAAAAAQERAADFAQAgDZcBAQAAAAGYAQEAAAABmgEAAACaAQKbAQEAAAABnAEBAAAAAZ0BCAAAAAGeAQIAAAABoAEAAACgAQKhAQEAAAABowEAAACjAQKkAQIAAAABpQFAAAAAAaYBQAAAAAEBEQAAxwEAMAERAADHAQAwDwYAAMECACAIAADCAgAglwEBALgCACGYAQEAuAIAIZoBAAC5ApoBIpsBAQC4AgAhnAEBALoCACGdAQgAuwIAIZ4BAgC8AgAhoAEAAL0CoAEioQEBALgCACGjAQAAvgKjASKkAQIAvwIAIaUBQADAAgAhpgFAAMACACECAAAAvQEAIBEAAMoBACANlwEBALgCACGYAQEAuAIAIZoBAAC5ApoBIpsBAQC4AgAhnAEBALoCACGdAQgAuwIAIZ4BAgC8AgAhoAEAAL0CoAEioQEBALgCACGjAQAAvgKjASKkAQIAvwIAIaUBQADAAgAhpgFAAMACACECAAAAwAEAIBEAAMwBACACAAAAwAEAIBEAAMwBACADAAAAvQEAIBgAAMUBACAZAADKAQAgAQAAAL0BACABAAAAwAEAIAcJAACzAgAgHgAAtgIAIB8AALUCACBgAAC0AgAgYQAAtwIAIJwBAACyAgAgpAEAALICACAQlAEAANYBADCVAQAA0wEAEJYBAADWAQAwlwEBANcBACGYAQEA1wEAIZoBAADYAZoBIpsBAQDXAQAhnAEBANkBACGdAQgA2gEAIZ4BAgDbAQAhoAEAANwBoAEioQEBANcBACGjAQAA3QGjASKkAQIA3gEAIaUBQADfAQAhpgFAAN8BACEDAAAAwAEAIAEAANIBADAdAADTAQAgAwAAAMABACABAADBAQAwAgAAvQEAIBCUAQAA1gEAMJUBAADTAQAQlgEAANYBADCXAQEA1wEAIZgBAQDXAQAhmgEAANgBmgEimwEBANcBACGcAQEA2QEAIZ0BCADaAQAhngECANsBACGgAQAA3AGgASKhAQEA1wEAIaMBAADdAaMBIqQBAgDeAQAhpQFAAN8BACGmAUAA3wEAIQ4JAADhAQAgHgAA8gEAIB8AAPIBACCnAQEAAAABqAEBAAAABKkBAQAAAASqAQEAAAABqwEBAAAAAawBAQAAAAGtAQEAAAABrgEBAPEBACGvAQEAAAABsAEBAAAAAbEBAQAAAAEHCQAA4QEAIB4AAPABACAfAADwAQAgpwEAAACaAQKoAQAAAJoBCKkBAAAAmgEIrgEAAO8BmgEiDgkAAOQBACAeAADuAQAgHwAA7gEAIKcBAQAAAAGoAQEAAAAFqQEBAAAABaoBAQAAAAGrAQEAAAABrAEBAAAAAa0BAQAAAAGuAQEA7QEAIa8BAQAAAAGwAQEAAAABsQEBAAAAAQ0JAADhAQAgHgAA6wEAIB8AAOsBACBgAADrAQAgYQAA6wEAIKcBCAAAAAGoAQgAAAAEqQEIAAAABKoBCAAAAAGrAQgAAAABrAEIAAAAAa0BCAAAAAGuAQgA7AEAIQ0JAADhAQAgHgAA4QEAIB8AAOEBACBgAADrAQAgYQAA4QEAIKcBAgAAAAGoAQIAAAAEqQECAAAABKoBAgAAAAGrAQIAAAABrAECAAAAAa0BAgAAAAGuAQIA6gEAIQcJAADhAQAgHgAA6QEAIB8AAOkBACCnAQAAAKABAqgBAAAAoAEIqQEAAACgAQiuAQAA6AGgASIHCQAA4QEAIB4AAOcBACAfAADnAQAgpwEAAACjAQKoAQAAAKMBCKkBAAAAowEIrgEAAOYBowEiDQkAAOQBACAeAADkAQAgHwAA5AEAIGAAAOUBACBhAADkAQAgpwECAAAAAagBAgAAAAWpAQIAAAAFqgECAAAAAasBAgAAAAGsAQIAAAABrQECAAAAAa4BAgDjAQAhCwkAAOEBACAeAADiAQAgHwAA4gEAIKcBQAAAAAGoAUAAAAAEqQFAAAAABKoBQAAAAAGrAUAAAAABrAFAAAAAAa0BQAAAAAGuAUAA4AEAIQsJAADhAQAgHgAA4gEAIB8AAOIBACCnAUAAAAABqAFAAAAABKkBQAAAAASqAUAAAAABqwFAAAAAAawBQAAAAAGtAUAAAAABrgFAAOABACEIpwECAAAAAagBAgAAAASpAQIAAAAEqgECAAAAAasBAgAAAAGsAQIAAAABrQECAAAAAa4BAgDhAQAhCKcBQAAAAAGoAUAAAAAEqQFAAAAABKoBQAAAAAGrAUAAAAABrAFAAAAAAa0BQAAAAAGuAUAA4gEAIQ0JAADkAQAgHgAA5AEAIB8AAOQBACBgAADlAQAgYQAA5AEAIKcBAgAAAAGoAQIAAAAFqQECAAAABaoBAgAAAAGrAQIAAAABrAECAAAAAa0BAgAAAAGuAQIA4wEAIQinAQIAAAABqAECAAAABakBAgAAAAWqAQIAAAABqwECAAAAAawBAgAAAAGtAQIAAAABrgECAOQBACEIpwEIAAAAAagBCAAAAAWpAQgAAAAFqgEIAAAAAasBCAAAAAGsAQgAAAABrQEIAAAAAa4BCADlAQAhBwkAAOEBACAeAADnAQAgHwAA5wEAIKcBAAAAowECqAEAAACjAQipAQAAAKMBCK4BAADmAaMBIgSnAQAAAKMBAqgBAAAAowEIqQEAAACjAQiuAQAA5wGjASIHCQAA4QEAIB4AAOkBACAfAADpAQAgpwEAAACgAQKoAQAAAKABCKkBAAAAoAEIrgEAAOgBoAEiBKcBAAAAoAECqAEAAACgAQipAQAAAKABCK4BAADpAaABIg0JAADhAQAgHgAA4QEAIB8AAOEBACBgAADrAQAgYQAA4QEAIKcBAgAAAAGoAQIAAAAEqQECAAAABKoBAgAAAAGrAQIAAAABrAECAAAAAa0BAgAAAAGuAQIA6gEAIQinAQgAAAABqAEIAAAABKkBCAAAAASqAQgAAAABqwEIAAAAAawBCAAAAAGtAQgAAAABrgEIAOsBACENCQAA4QEAIB4AAOsBACAfAADrAQAgYAAA6wEAIGEAAOsBACCnAQgAAAABqAEIAAAABKkBCAAAAASqAQgAAAABqwEIAAAAAawBCAAAAAGtAQgAAAABrgEIAOwBACEOCQAA5AEAIB4AAO4BACAfAADuAQAgpwEBAAAAAagBAQAAAAWpAQEAAAAFqgEBAAAAAasBAQAAAAGsAQEAAAABrQEBAAAAAa4BAQDtAQAhrwEBAAAAAbABAQAAAAGxAQEAAAABC6cBAQAAAAGoAQEAAAAFqQEBAAAABaoBAQAAAAGrAQEAAAABrAEBAAAAAa0BAQAAAAGuAQEA7gEAIa8BAQAAAAGwAQEAAAABsQEBAAAAAQcJAADhAQAgHgAA8AEAIB8AAPABACCnAQAAAJoBAqgBAAAAmgEIqQEAAACaAQiuAQAA7wGaASIEpwEAAACaAQKoAQAAAJoBCKkBAAAAmgEIrgEAAPABmgEiDgkAAOEBACAeAADyAQAgHwAA8gEAIKcBAQAAAAGoAQEAAAAEqQEBAAAABKoBAQAAAAGrAQEAAAABrAEBAAAAAa0BAQAAAAGuAQEA8QEAIa8BAQAAAAGwAQEAAAABsQEBAAAAAQunAQEAAAABqAEBAAAABKkBAQAAAASqAQEAAAABqwEBAAAAAawBAQAAAAGtAQEAAAABrgEBAPIBACGvAQEAAAABsAEBAAAAAbEBAQAAAAESBgAA_QEAIAgAAP4BACCUAQAA8wEAMJUBAADAAQAQlgEAAPMBADCXAQEA9AEAIZgBAQD0AQAhmgEAAPUBmgEimwEBAPQBACGcAQEA9gEAIZ0BCAD3AQAhngECAPgBACGgAQAA-QGgASKhAQEA9AEAIaMBAAD6AaMBIqQBAgD7AQAhpQFAAPwBACGmAUAA_AEAIQunAQEAAAABqAEBAAAABKkBAQAAAASqAQEAAAABqwEBAAAAAawBAQAAAAGtAQEAAAABrgEBAPIBACGvAQEAAAABsAEBAAAAAbEBAQAAAAEEpwEAAACaAQKoAQAAAJoBCKkBAAAAmgEIrgEAAPABmgEiC6cBAQAAAAGoAQEAAAAFqQEBAAAABaoBAQAAAAGrAQEAAAABrAEBAAAAAa0BAQAAAAGuAQEA7gEAIa8BAQAAAAGwAQEAAAABsQEBAAAAAQinAQgAAAABqAEIAAAABKkBCAAAAASqAQgAAAABqwEIAAAAAawBCAAAAAGtAQgAAAABrgEIAOsBACEIpwECAAAAAagBAgAAAASpAQIAAAAEqgECAAAAAasBAgAAAAGsAQIAAAABrQECAAAAAa4BAgDhAQAhBKcBAAAAoAECqAEAAACgAQipAQAAAKABCK4BAADpAaABIgSnAQAAAKMBAqgBAAAAowEIqQEAAACjAQiuAQAA5wGjASIIpwECAAAAAagBAgAAAAWpAQIAAAAFqgECAAAAAasBAgAAAAGsAQIAAAABrQECAAAAAa4BAgDkAQAhCKcBQAAAAAGoAUAAAAAEqQFAAAAABKoBQAAAAAGrAUAAAAABrAFAAAAAAa0BQAAAAAGuAUAA4gEAIQOyAQAACwAgswEAAAsAILQBAAALACADsgEAABAAILMBAAAQACC0AQAAEAAgCpQBAAD_AQAwlQEAALoBABCWAQAA_wEAMJcBAQDXAQAhpQFAAN8BACGmAUAA3wEAIbUBAQDXAQAhtgEBANcBACG3AQIA2wEAIbgBAQDZAQAhDJQBAACAAgAwlQEAAKQBABCWAQAAgAIAMJcBAQDXAQAhowEAAIICvQEipQFAAN8BACGmAUAA3wEAIbkBCADaAQAhugEBAIECACG7AQEA2QEAIb0BAACDAgAgvgEBANcBACELCQAA4QEAIB4AAPIBACAfAADyAQAgpwEBAAAAAagBAQAAAASpAQEAAAAEqgEBAAAAAasBAQAAAAGsAQEAAAABrQEBAAAAAa4BAQCHAgAhBwkAAOEBACAeAACGAgAgHwAAhgIAIKcBAAAAvQECqAEAAAC9AQipAQAAAL0BCK4BAACFAr0BIg8JAADkAQAgHgAAhAIAIB8AAIQCACCnAYAAAAABqgGAAAAAAasBgAAAAAGsAYAAAAABrQGAAAAAAa4BgAAAAAG_AQEAAAABwAEBAAAAAcEBAQAAAAHCAYAAAAABwwGAAAAAAcQBgAAAAAEMpwGAAAAAAaoBgAAAAAGrAYAAAAABrAGAAAAAAa0BgAAAAAGuAYAAAAABvwEBAAAAAcABAQAAAAHBAQEAAAABwgGAAAAAAcMBgAAAAAHEAYAAAAABBwkAAOEBACAeAACGAgAgHwAAhgIAIKcBAAAAvQECqAEAAAC9AQipAQAAAL0BCK4BAACFAr0BIgSnAQAAAL0BAqgBAAAAvQEIqQEAAAC9AQiuAQAAhgK9ASILCQAA4QEAIB4AAPIBACAfAADyAQAgpwEBAAAAAagBAQAAAASpAQEAAAAEqgEBAAAAAasBAQAAAAGsAQEAAAABrQEBAAAAAa4BAQCHAgAhDQoAAIsCACCUAQAAiAIAMJUBAAAWABCWAQAAiAIAMJcBAQD0AQAhowEAAIkCvQEipQFAAPwBACGmAUAA_AEAIbkBCAD3AQAhugEBAKcCACG7AQEA9gEAIb0BAACKAgAgvgEBAPQBACEEpwEAAAC9AQKoAQAAAL0BCKkBAAAAvQEIrgEAAIYCvQEiDKcBgAAAAAGqAYAAAAABqwGAAAAAAawBgAAAAAGtAYAAAAABrgGAAAAAAb8BAQAAAAHAAQEAAAABwQEBAAAAAcIBgAAAAAHDAYAAAAABxAGAAAAAARQDAACqAgAgBwAAqwIAIAsAAK8CACCUAQAArAIAMJUBAAALABCWAQAArAIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACHFAUAA_AEAIcYBQAD8AQAhxwECAPgBACHIARAArQIAIcoBAACuAsoBIssBAACJAr0BIswBAQD2AQAh5AEAAAsAIOUBAAALACAPlAEAAIwCADCVAQAAjAEAEJYBAACMAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAhtQEBANcBACG2AQEA1wEAIcUBQADfAQAhxgFAAN8BACHHAQIA2wEAIcgBEACNAgAhygEAAI4CygEiywEAAIICvQEizAEBANkBACENCQAA4QEAIB4AAJICACAfAACSAgAgYAAAkgIAIGEAAJICACCnARAAAAABqAEQAAAABKkBEAAAAASqARAAAAABqwEQAAAAAawBEAAAAAGtARAAAAABrgEQAJECACEHCQAA4QEAIB4AAJACACAfAACQAgAgpwEAAADKAQKoAQAAAMoBCKkBAAAAygEIrgEAAI8CygEiBwkAAOEBACAeAACQAgAgHwAAkAIAIKcBAAAAygECqAEAAADKAQipAQAAAMoBCK4BAACPAsoBIgSnAQAAAMoBAqgBAAAAygEIqQEAAADKAQiuAQAAkALKASINCQAA4QEAIB4AAJICACAfAACSAgAgYAAAkgIAIGEAAJICACCnARAAAAABqAEQAAAABKkBEAAAAASqARAAAAABqwEQAAAAAawBEAAAAAGtARAAAAABrgEQAJECACEIpwEQAAAAAagBEAAAAASpARAAAAAEqgEQAAAAAasBEAAAAAGsARAAAAABrQEQAAAAAa4BEACSAgAhCZQBAACTAgAwlQEAAHYAEJYBAACTAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAhzQEBANcBACHOAQEA1wEAIc8BQADfAQAhCZQBAACUAgAwlQEAAGMAEJYBAACUAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhzQEBAPQBACHOAQEA9AEAIc8BQAD8AQAhEJQBAACVAgAwlQEAAF0AEJYBAACVAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAhtQEBANcBACHQAQEA1wEAIdEBAQDXAQAh0gEBANkBACHTAQEA2QEAIdQBAQDZAQAh1QFAAJYCACHWAUAAlgIAIdcBAQDZAQAh2AEBANkBACELCQAA5AEAIB4AAJgCACAfAACYAgAgpwFAAAAAAagBQAAAAAWpAUAAAAAFqgFAAAAAAasBQAAAAAGsAUAAAAABrQFAAAAAAa4BQACXAgAhCwkAAOQBACAeAACYAgAgHwAAmAIAIKcBQAAAAAGoAUAAAAAFqQFAAAAABaoBQAAAAAGrAUAAAAABrAFAAAAAAa0BQAAAAAGuAUAAlwIAIQinAUAAAAABqAFAAAAABakBQAAAAAWqAUAAAAABqwFAAAAAAawBQAAAAAGtAUAAAAABrgFAAJgCACELlAEAAJkCADCVAQAARwAQlgEAAJkCADCXAQEA1wEAIaUBQADfAQAhpgFAAN8BACG1AQEA1wEAIc8BQADfAQAh2QEBANcBACHaAQEA2QEAIdsBAQDZAQAhDZQBAACaAgAwlQEAADEAEJYBAACaAgAwlwEBANcBACGlAUAA3wEAIaYBQADfAQAh3AEBANcBACHdAQEA1wEAId4BIACbAgAh3wEBANkBACHhAQAAnALhASLiASAAmwIAIeMBQACWAgAhBQkAAOEBACAeAACgAgAgHwAAoAIAIKcBIAAAAAGuASAAnwIAIQcJAADhAQAgHgAAngIAIB8AAJ4CACCnAQAAAOEBAqgBAAAA4QEIqQEAAADhAQiuAQAAnQLhASIHCQAA4QEAIB4AAJ4CACAfAACeAgAgpwEAAADhAQKoAQAAAOEBCKkBAAAA4QEIrgEAAJ0C4QEiBKcBAAAA4QECqAEAAADhAQipAQAAAOEBCK4BAACeAuEBIgUJAADhAQAgHgAAoAIAIB8AAKACACCnASAAAAABrgEgAJ8CACECpwEgAAAAAa4BIACgAgAhEQQAAKUCACAFAACmAgAgBgAA_QEAIAgAAP4BACCUAQAAoQIAMJUBAAAeABCWAQAAoQIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIdwBAQD0AQAh3QEBAPQBACHeASAAogIAId8BAQD2AQAh4QEAAKMC4QEi4gEgAKICACHjAUAApAIAIQKnASAAAAABrgEgAKACACEEpwEAAADhAQKoAQAAAOEBCKkBAAAA4QEIrgEAAJ4C4QEiCKcBQAAAAAGoAUAAAAAFqQFAAAAABaoBQAAAAAGrAUAAAAABrAFAAAAAAa0BQAAAAAGuAUAAmAIAIQOyAQAAAwAgswEAAAMAILQBAAADACADsgEAAAcAILMBAAAHACC0AQAABwAgCKcBAQAAAAGoAQEAAAAEqQEBAAAABKoBAQAAAAGrAQEAAAABrAEBAAAAAa0BAQAAAAGuAQEAqAIAIQinAQEAAAABqAEBAAAABKkBAQAAAASqAQEAAAABqwEBAAAAAawBAQAAAAGtAQEAAAABrgEBAKgCACEMAwAAqgIAIAcAAKsCACCUAQAAqQIAMJUBAAAQABCWAQAAqQIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACG3AQIA-AEAIbgBAQD2AQAhEwQAAKUCACAFAACmAgAgBgAA_QEAIAgAAP4BACCUAQAAoQIAMJUBAAAeABCWAQAAoQIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIdwBAQD0AQAh3QEBAPQBACHeASAAogIAId8BAQD2AQAh4QEAAKMC4QEi4gEgAKICACHjAUAApAIAIeQBAAAeACDlAQAAHgAgFAYAAP0BACAIAAD-AQAglAEAAPMBADCVAQAAwAEAEJYBAADzAQAwlwEBAPQBACGYAQEA9AEAIZoBAAD1AZoBIpsBAQD0AQAhnAEBAPYBACGdAQgA9wEAIZ4BAgD4AQAhoAEAAPkBoAEioQEBAPQBACGjAQAA-gGjASKkAQIA-wEAIaUBQAD8AQAhpgFAAPwBACHkAQAAwAEAIOUBAADAAQAgEgMAAKoCACAHAACrAgAgCwAArwIAIJQBAACsAgAwlQEAAAsAEJYBAACsAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACG2AQEA9AEAIcUBQAD8AQAhxgFAAPwBACHHAQIA-AEAIcgBEACtAgAhygEAAK4CygEiywEAAIkCvQEizAEBAPYBACEIpwEQAAAAAagBEAAAAASpARAAAAAEqgEQAAAAAasBEAAAAAGsARAAAAABrQEQAAAAAa4BEACSAgAhBKcBAAAAygECqAEAAADKAQipAQAAAMoBCK4BAACQAsoBIg8KAACLAgAglAEAAIgCADCVAQAAFgAQlgEAAIgCADCXAQEA9AEAIaMBAACJAr0BIqUBQAD8AQAhpgFAAPwBACG5AQgA9wEAIboBAQCnAgAhuwEBAPYBACG9AQAAigIAIL4BAQD0AQAh5AEAABYAIOUBAAAWACARAwAAqgIAIJQBAACwAgAwlQEAAAcAEJYBAACwAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHQAQEA9AEAIdEBAQD0AQAh0gEBAPYBACHTAQEA9gEAIdQBAQD2AQAh1QFAAKQCACHWAUAApAIAIdcBAQD2AQAh2AEBAPYBACEMAwAAqgIAIJQBAACxAgAwlQEAAAMAEJYBAACxAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHPAUAA_AEAIdkBAQD0AQAh2gEBAPYBACHbAQEA9gEAIQAAAAAAAAHpAQEAAAABAekBAAAAmgECAekBAQAAAAEF6QEIAAAAAe8BCAAAAAHwAQgAAAAB8QEIAAAAAfIBCAAAAAEF6QECAAAAAe8BAgAAAAHwAQIAAAAB8QECAAAAAfIBAgAAAAEB6QEAAACgAQIB6QEAAACjAQIF6QECAAAAAe8BAgAAAAHwAQIAAAAB8QECAAAAAfIBAgAAAAEB6QFAAAAAAQsYAADRAgAwGQAA1gIAMOYBAADSAgAw5wEAANMCADDoAQAA1AIAIOkBAADVAgAw6gEAANUCADDrAQAA1QIAMOwBAADVAgAw7QEAANcCADDuAQAA2AIAMAsYAADDAgAwGQAAyAIAMOYBAADEAgAw5wEAAMUCADDoAQAAxgIAIOkBAADHAgAw6gEAAMcCADDrAQAAxwIAMOwBAADHAgAw7QEAAMkCADDuAQAAygIAMAcDAADQAgAglwEBAAAAAaUBQAAAAAGmAUAAAAABtQEBAAAAAbcBAgAAAAG4AQEAAAABAgAAABIAIBgAAM8CACADAAAAEgAgGAAAzwIAIBkAAM0CACABEQAA9QMAMAwDAACqAgAgBwAAqwIAIJQBAACpAgAwlQEAABAAEJYBAACpAgAwlwEBAAAAAaUBQAD8AQAhpgFAAPwBACG1AQEA9AEAIbYBAQD0AQAhtwECAPgBACG4AQEA9gEAIQIAAAASACARAADNAgAgAgAAAMsCACARAADMAgAgCpQBAADKAgAwlQEAAMsCABCWAQAAygIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACG3AQIA-AEAIbgBAQD2AQAhCpQBAADKAgAwlQEAAMsCABCWAQAAygIAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACG3AQIA-AEAIbgBAQD2AQAhBpcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbUBAQC4AgAhtwECALwCACG4AQEAugIAIQcDAADOAgAglwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACG3AQIAvAIAIbgBAQC6AgAhBRgAAPADACAZAADzAwAg5gEAAPEDACDnAQAA8gMAIOwBAAABACAHAwAA0AIAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAG3AQIAAAABuAEBAAAAAQMYAADwAwAg5gEAAPEDACDsAQAAAQAgDQMAAOcCACALAADoAgAglwEBAAAAAaUBQAAAAAGmAUAAAAABtQEBAAAAAcUBQAAAAAHGAUAAAAABxwECAAAAAcgBEAAAAAHKAQAAAMoBAssBAAAAvQECzAEBAAAAAQIAAAANACAYAADmAgAgAwAAAA0AIBgAAOYCACAZAADeAgAgAREAAO8DADASAwAAqgIAIAcAAKsCACALAACvAgAglAEAAKwCADCVAQAACwAQlgEAAKwCADCXAQEAAAABpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAhtgEBAPQBACHFAUAA_AEAIcYBQAD8AQAhxwECAPgBACHIARAArQIAIcoBAACuAsoBIssBAACJAr0BIswBAQD2AQAhAgAAAA0AIBEAAN4CACACAAAA2QIAIBEAANoCACAPlAEAANgCADCVAQAA2QIAEJYBAADYAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACG2AQEA9AEAIcUBQAD8AQAhxgFAAPwBACHHAQIA-AEAIcgBEACtAgAhygEAAK4CygEiywEAAIkCvQEizAEBAPYBACEPlAEAANgCADCVAQAA2QIAEJYBAADYAgAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACG2AQEA9AEAIcUBQAD8AQAhxgFAAPwBACHHAQIA-AEAIcgBEACtAgAhygEAAK4CygEiywEAAIkCvQEizAEBAPYBACELlwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACHFAUAAwAIAIcYBQADAAgAhxwECALwCACHIARAA2wIAIcoBAADcAsoBIssBAADdAr0BIswBAQC6AgAhBekBEAAAAAHvARAAAAAB8AEQAAAAAfEBEAAAAAHyARAAAAABAekBAAAAygECAekBAAAAvQECDQMAAN8CACALAADgAgAglwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACHFAUAAwAIAIcYBQADAAgAhxwECALwCACHIARAA2wIAIcoBAADcAsoBIssBAADdAr0BIswBAQC6AgAhBRgAAOoDACAZAADtAwAg5gEAAOsDACDnAQAA7AMAIOwBAAABACAHGAAA4QIAIBkAAOQCACDmAQAA4gIAIOcBAADjAgAg6gEAABYAIOsBAAAWACDsAQAAjwEAIAiXAQEAAAABowEAAAC9AQKlAUAAAAABpgFAAAAAAbkBCAAAAAG6AQEAAAABuwEBAAAAAb0BgAAAAAECAAAAjwEAIBgAAOECACADAAAAFgAgGAAA4QIAIBkAAOUCACAKAAAAFgAgEQAA5QIAIJcBAQC4AgAhowEAAN0CvQEipQFAAMACACGmAUAAwAIAIbkBCAC7AgAhugEBALgCACG7AQEAugIAIb0BgAAAAAEIlwEBALgCACGjAQAA3QK9ASKlAUAAwAIAIaYBQADAAgAhuQEIALsCACG6AQEAuAIAIbsBAQC6AgAhvQGAAAAAAQ0DAADnAgAgCwAA6AIAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAHFAUAAAAABxgFAAAAAAccBAgAAAAHIARAAAAABygEAAADKAQLLAQAAAL0BAswBAQAAAAEDGAAA6gMAIOYBAADrAwAg7AEAAAEAIAMYAADhAgAg5gEAAOICACDsAQAAjwEAIAQYAADRAgAw5gEAANICADDoAQAA1AIAIOwBAADVAgAwBBgAAMMCADDmAQAAxAIAMOgBAADGAgAg7AEAAMcCADAAAAAAAAAABRgAAOUDACAZAADoAwAg5gEAAOYDACDnAQAA5wMAIOwBAAC9AQAgAxgAAOUDACDmAQAA5gMAIOwBAAC9AQAgAAAAAAAFGAAA4AMAIBkAAOMDACDmAQAA4QMAIOcBAADiAwAg7AEAAA0AIAMYAADgAwAg5gEAAOEDACDsAQAADQAgBAMAAMoDACAHAADLAwAgCwAAzAMAIMwBAACyAgAgAAAAAAAFGAAA2wMAIBkAAN4DACDmAQAA3AMAIOcBAADdAwAg7AEAAL0BACADGAAA2wMAIOYBAADcAwAg7AEAAL0BACAAAAAAAAAB6QFAAAAAAQUYAADWAwAgGQAA2QMAIOYBAADXAwAg5wEAANgDACDsAQAAAQAgAxgAANYDACDmAQAA1wMAIOwBAAABACAAAAAFGAAA0QMAIBkAANQDACDmAQAA0gMAIOcBAADTAwAg7AEAAAEAIAMYAADRAwAg5gEAANIDACDsAQAAAQAgAAAAAekBIAAAAAEB6QEAAADhAQILGAAAuAMAMBkAAL0DADDmAQAAuQMAMOcBAAC6AwAw6AEAALsDACDpAQAAvAMAMOoBAAC8AwAw6wEAALwDADDsAQAAvAMAMO0BAAC-AwAw7gEAAL8DADALGAAArAMAMBkAALEDADDmAQAArQMAMOcBAACuAwAw6AEAAK8DACDpAQAAsAMAMOoBAACwAwAw6wEAALADADDsAQAAsAMAMO0BAACyAwAw7gEAALMDADALGAAAowMAMBkAAKcDADDmAQAApAMAMOcBAAClAwAw6AEAAKYDACDpAQAA1QIAMOoBAADVAgAw6wEAANUCADDsAQAA1QIAMO0BAACoAwAw7gEAANgCADALGAAAmgMAMBkAAJ4DADDmAQAAmwMAMOcBAACcAwAw6AEAAJ0DACDpAQAAxwIAMOoBAADHAgAw6wEAAMcCADDsAQAAxwIAMO0BAACfAwAw7gEAAMoCADAHBwAA8wIAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbYBAQAAAAG3AQIAAAABuAEBAAAAAQIAAAASACAYAACiAwAgAwAAABIAIBgAAKIDACAZAAChAwAgAREAANADADACAAAAEgAgEQAAoQMAIAIAAADLAgAgEQAAoAMAIAaXAQEAuAIAIaUBQADAAgAhpgFAAMACACG2AQEAuAIAIbcBAgC8AgAhuAEBALoCACEHBwAA8gIAIJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIbYBAQC4AgAhtwECALwCACG4AQEAugIAIQcHAADzAgAglwEBAAAAAaUBQAAAAAGmAUAAAAABtgEBAAAAAbcBAgAAAAG4AQEAAAABDQcAAIIDACALAADoAgAglwEBAAAAAaUBQAAAAAGmAUAAAAABtgEBAAAAAcUBQAAAAAHGAUAAAAABxwECAAAAAcgBEAAAAAHKAQAAAMoBAssBAAAAvQECzAEBAAAAAQIAAAANACAYAACrAwAgAwAAAA0AIBgAAKsDACAZAACqAwAgAREAAM8DADACAAAADQAgEQAAqgMAIAIAAADZAgAgEQAAqQMAIAuXAQEAuAIAIaUBQADAAgAhpgFAAMACACG2AQEAuAIAIcUBQADAAgAhxgFAAMACACHHAQIAvAIAIcgBEADbAgAhygEAANwCygEiywEAAN0CvQEizAEBALoCACENBwAAgQMAIAsAAOACACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACG2AQEAuAIAIcUBQADAAgAhxgFAAMACACHHAQIAvAIAIcgBEADbAgAhygEAANwCygEiywEAAN0CvQEizAEBALoCACENBwAAggMAIAsAAOgCACCXAQEAAAABpQFAAAAAAaYBQAAAAAG2AQEAAAABxQFAAAAAAcYBQAAAAAHHAQIAAAAByAEQAAAAAcoBAAAAygECywEAAAC9AQLMAQEAAAABDJcBAQAAAAGlAUAAAAABpgFAAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQEAAAAB1QFAAAAAAdYBQAAAAAHXAQEAAAAB2AEBAAAAAQIAAAAJACAYAAC3AwAgAwAAAAkAIBgAALcDACAZAAC2AwAgAREAAM4DADARAwAAqgIAIJQBAACwAgAwlQEAAAcAEJYBAACwAgAwlwEBAAAAAaUBQAD8AQAhpgFAAPwBACG1AQEA9AEAIdABAQD0AQAh0QEBAPQBACHSAQEA9gEAIdMBAQD2AQAh1AEBAPYBACHVAUAApAIAIdYBQACkAgAh1wEBAPYBACHYAQEA9gEAIQIAAAAJACARAAC2AwAgAgAAALQDACARAAC1AwAgEJQBAACzAwAwlQEAALQDABCWAQAAswMAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAh0AEBAPQBACHRAQEA9AEAIdIBAQD2AQAh0wEBAPYBACHUAQEA9gEAIdUBQACkAgAh1gFAAKQCACHXAQEA9gEAIdgBAQD2AQAhEJQBAACzAwAwlQEAALQDABCWAQAAswMAMJcBAQD0AQAhpQFAAPwBACGmAUAA_AEAIbUBAQD0AQAh0AEBAPQBACHRAQEA9AEAIdIBAQD2AQAh0wEBAPYBACHUAQEA9gEAIdUBQACkAgAh1gFAAKQCACHXAQEA9gEAIdgBAQD2AQAhDJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIdABAQC4AgAh0QEBALgCACHSAQEAugIAIdMBAQC6AgAh1AEBALoCACHVAUAAiQMAIdYBQACJAwAh1wEBALoCACHYAQEAugIAIQyXAQEAuAIAIaUBQADAAgAhpgFAAMACACHQAQEAuAIAIdEBAQC4AgAh0gEBALoCACHTAQEAugIAIdQBAQC6AgAh1QFAAIkDACHWAUAAiQMAIdcBAQC6AgAh2AEBALoCACEMlwEBAAAAAaUBQAAAAAGmAUAAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAAB0wEBAAAAAdQBAQAAAAHVAUAAAAAB1gFAAAAAAdcBAQAAAAHYAQEAAAABB5cBAQAAAAGlAUAAAAABpgFAAAAAAc8BQAAAAAHZAQEAAAAB2gEBAAAAAdsBAQAAAAECAAAABQAgGAAAwwMAIAMAAAAFACAYAADDAwAgGQAAwgMAIAERAADNAwAwDAMAAKoCACCUAQAAsQIAMJUBAAADABCWAQAAsQIAMJcBAQAAAAGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHPAUAA_AEAIdkBAQAAAAHaAQEA9gEAIdsBAQD2AQAhAgAAAAUAIBEAAMIDACACAAAAwAMAIBEAAMEDACALlAEAAL8DADCVAQAAwAMAEJYBAAC_AwAwlwEBAPQBACGlAUAA_AEAIaYBQAD8AQAhtQEBAPQBACHPAUAA_AEAIdkBAQD0AQAh2gEBAPYBACHbAQEA9gEAIQuUAQAAvwMAMJUBAADAAwAQlgEAAL8DADCXAQEA9AEAIaUBQAD8AQAhpgFAAPwBACG1AQEA9AEAIc8BQAD8AQAh2QEBAPQBACHaAQEA9gEAIdsBAQD2AQAhB5cBAQC4AgAhpQFAAMACACGmAUAAwAIAIc8BQADAAgAh2QEBALgCACHaAQEAugIAIdsBAQC6AgAhB5cBAQC4AgAhpQFAAMACACGmAUAAwAIAIc8BQADAAgAh2QEBALgCACHaAQEAugIAIdsBAQC6AgAhB5cBAQAAAAGlAUAAAAABpgFAAAAAAc8BQAAAAAHZAQEAAAAB2gEBAAAAAdsBAQAAAAEEGAAAuAMAMOYBAAC5AwAw6AEAALsDACDsAQAAvAMAMAQYAACsAwAw5gEAAK0DADDoAQAArwMAIOwBAACwAwAwBBgAAKMDADDmAQAApAMAMOgBAACmAwAg7AEAANUCADAEGAAAmgMAMOYBAACbAwAw6AEAAJ0DACDsAQAAxwIAMAAABgQAAMgDACAFAADJAwAgBgAA6wIAIAgAAOwCACDfAQAAsgIAIOMBAACyAgAgBAYAAOsCACAIAADsAgAgnAEAALICACCkAQAAsgIAIAMKAAD7AgAguwEAALICACC9AQAAsgIAIAeXAQEAAAABpQFAAAAAAaYBQAAAAAHPAUAAAAAB2QEBAAAAAdoBAQAAAAHbAQEAAAABDJcBAQAAAAGlAUAAAAABpgFAAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQEAAAAB1QFAAAAAAdYBQAAAAAHXAQEAAAAB2AEBAAAAAQuXAQEAAAABpQFAAAAAAaYBQAAAAAG2AQEAAAABxQFAAAAAAcYBQAAAAAHHAQIAAAAByAEQAAAAAcoBAAAAygECywEAAAC9AQLMAQEAAAABBpcBAQAAAAGlAUAAAAABpgFAAAAAAbYBAQAAAAG3AQIAAAABuAEBAAAAAQ0FAADFAwAgBgAAxgMAIAgAAMcDACCXAQEAAAABpQFAAAAAAaYBQAAAAAHcAQEAAAAB3QEBAAAAAd4BIAAAAAHfAQEAAAAB4QEAAADhAQLiASAAAAAB4wFAAAAAAQIAAAABACAYAADRAwAgAwAAAB4AIBgAANEDACAZAADVAwAgDwAAAB4AIAUAAJcDACAGAACYAwAgCAAAmQMAIBEAANUDACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACHcAQEAuAIAId0BAQC4AgAh3gEgAJQDACHfAQEAugIAIeEBAACVA-EBIuIBIACUAwAh4wFAAIkDACENBQAAlwMAIAYAAJgDACAIAACZAwAglwEBALgCACGlAUAAwAIAIaYBQADAAgAh3AEBALgCACHdAQEAuAIAId4BIACUAwAh3wEBALoCACHhAQAAlQPhASLiASAAlAMAIeMBQACJAwAhDQQAAMQDACAGAADGAwAgCAAAxwMAIJcBAQAAAAGlAUAAAAABpgFAAAAAAdwBAQAAAAHdAQEAAAAB3gEgAAAAAd8BAQAAAAHhAQAAAOEBAuIBIAAAAAHjAUAAAAABAgAAAAEAIBgAANYDACADAAAAHgAgGAAA1gMAIBkAANoDACAPAAAAHgAgBAAAlgMAIAYAAJgDACAIAACZAwAgEQAA2gMAIJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIdwBAQC4AgAh3QEBALgCACHeASAAlAMAId8BAQC6AgAh4QEAAJUD4QEi4gEgAJQDACHjAUAAiQMAIQ0EAACWAwAgBgAAmAMAIAgAAJkDACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACHcAQEAuAIAId0BAQC4AgAh3gEgAJQDACHfAQEAugIAIeEBAACVA-EBIuIBIACUAwAh4wFAAIkDACEOCAAA6gIAIJcBAQAAAAGYAQEAAAABmgEAAACaAQKbAQEAAAABnAEBAAAAAZ0BCAAAAAGeAQIAAAABoAEAAACgAQKhAQEAAAABowEAAACjAQKkAQIAAAABpQFAAAAAAaYBQAAAAAECAAAAvQEAIBgAANsDACADAAAAwAEAIBgAANsDACAZAADfAwAgEAAAAMABACAIAADCAgAgEQAA3wMAIJcBAQC4AgAhmAEBALgCACGaAQAAuQKaASKbAQEAuAIAIZwBAQC6AgAhnQEIALsCACGeAQIAvAIAIaABAAC9AqABIqEBAQC4AgAhowEAAL4CowEipAECAL8CACGlAUAAwAIAIaYBQADAAgAhDggAAMICACCXAQEAuAIAIZgBAQC4AgAhmgEAALkCmgEimwEBALgCACGcAQEAugIAIZ0BCAC7AgAhngECALwCACGgAQAAvQKgASKhAQEAuAIAIaMBAAC-AqMBIqQBAgC_AgAhpQFAAMACACGmAUAAwAIAIQ4DAADnAgAgBwAAggMAIJcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAG2AQEAAAABxQFAAAAAAcYBQAAAAAHHAQIAAAAByAEQAAAAAcoBAAAAygECywEAAAC9AQLMAQEAAAABAgAAAA0AIBgAAOADACADAAAACwAgGAAA4AMAIBkAAOQDACAQAAAACwAgAwAA3wIAIAcAAIEDACARAADkAwAglwEBALgCACGlAUAAwAIAIaYBQADAAgAhtQEBALgCACG2AQEAuAIAIcUBQADAAgAhxgFAAMACACHHAQIAvAIAIcgBEADbAgAhygEAANwCygEiywEAAN0CvQEizAEBALoCACEOAwAA3wIAIAcAAIEDACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACG1AQEAuAIAIbYBAQC4AgAhxQFAAMACACHGAUAAwAIAIccBAgC8AgAhyAEQANsCACHKAQAA3ALKASLLAQAA3QK9ASLMAQEAugIAIQ4GAADpAgAglwEBAAAAAZgBAQAAAAGaAQAAAJoBApsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BAgAAAAGgAQAAAKABAqEBAQAAAAGjAQAAAKMBAqQBAgAAAAGlAUAAAAABpgFAAAAAAQIAAAC9AQAgGAAA5QMAIAMAAADAAQAgGAAA5QMAIBkAAOkDACAQAAAAwAEAIAYAAMECACARAADpAwAglwEBALgCACGYAQEAuAIAIZoBAAC5ApoBIpsBAQC4AgAhnAEBALoCACGdAQgAuwIAIZ4BAgC8AgAhoAEAAL0CoAEioQEBALgCACGjAQAAvgKjASKkAQIAvwIAIaUBQADAAgAhpgFAAMACACEOBgAAwQIAIJcBAQC4AgAhmAEBALgCACGaAQAAuQKaASKbAQEAuAIAIZwBAQC6AgAhnQEIALsCACGeAQIAvAIAIaABAAC9AqABIqEBAQC4AgAhowEAAL4CowEipAECAL8CACGlAUAAwAIAIaYBQADAAgAhDQQAAMQDACAFAADFAwAgCAAAxwMAIJcBAQAAAAGlAUAAAAABpgFAAAAAAdwBAQAAAAHdAQEAAAAB3gEgAAAAAd8BAQAAAAHhAQAAAOEBAuIBIAAAAAHjAUAAAAABAgAAAAEAIBgAAOoDACADAAAAHgAgGAAA6gMAIBkAAO4DACAPAAAAHgAgBAAAlgMAIAUAAJcDACAIAACZAwAgEQAA7gMAIJcBAQC4AgAhpQFAAMACACGmAUAAwAIAIdwBAQC4AgAh3QEBALgCACHeASAAlAMAId8BAQC6AgAh4QEAAJUD4QEi4gEgAJQDACHjAUAAiQMAIQ0EAACWAwAgBQAAlwMAIAgAAJkDACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACHcAQEAuAIAId0BAQC4AgAh3gEgAJQDACHfAQEAugIAIeEBAACVA-EBIuIBIACUAwAh4wFAAIkDACELlwEBAAAAAaUBQAAAAAGmAUAAAAABtQEBAAAAAcUBQAAAAAHGAUAAAAABxwECAAAAAcgBEAAAAAHKAQAAAMoBAssBAAAAvQECzAEBAAAAAQ0EAADEAwAgBQAAxQMAIAYAAMYDACCXAQEAAAABpQFAAAAAAaYBQAAAAAHcAQEAAAAB3QEBAAAAAd4BIAAAAAHfAQEAAAAB4QEAAADhAQLiASAAAAAB4wFAAAAAAQIAAAABACAYAADwAwAgAwAAAB4AIBgAAPADACAZAAD0AwAgDwAAAB4AIAQAAJYDACAFAACXAwAgBgAAmAMAIBEAAPQDACCXAQEAuAIAIaUBQADAAgAhpgFAAMACACHcAQEAuAIAId0BAQC4AgAh3gEgAJQDACHfAQEAugIAIeEBAACVA-EBIuIBIACUAwAh4wFAAIkDACENBAAAlgMAIAUAAJcDACAGAACYAwAglwEBALgCACGlAUAAwAIAIaYBQADAAgAh3AEBALgCACHdAQEAuAIAId4BIACUAwAh3wEBALoCACHhAQAAlQPhASLiASAAlAMAIeMBQACJAwAhBpcBAQAAAAGlAUAAAAABpgFAAAAAAbUBAQAAAAG3AQIAAAABuAEBAAAAAQUEBgIFCgMGDgQIGAYJAAkBAwABAQMAAQMDAAEHAAULFwgDBg8ECBMGCQAHAgMAAQcABQIGFAAIFQABCgAEBAQZAAUaAAYbAAgcAAAAAAMJAA4eAA8fABAAAAADCQAOHgAPHwAQAQMAAQEDAAEDCQAVHgAWHwAXAAAAAwkAFR4AFh8AFwEDAAEBAwABAwkAHB4AHR8AHgAAAAMJABweAB0fAB4AAAADCQAkHgAlHwAmAAAAAwkAJB4AJR8AJgIDAAEHAAUCAwABBwAFBQkAKx4ALh8AL2AALGEALQAAAAAABQkAKx4ALh8AL2AALGEALQEKAAQBCgAEBQkANB4ANx8AOGAANWEANgAAAAAABQkANB4ANx8AOGAANWEANgIDAAEHAAUCAwABBwAFBQkAPR4AQB8AQWAAPmEAPwAAAAAABQkAPR4AQB8AQWAAPmEAPwAABQkARh4ASR8ASmAAR2EASAAAAAAABQkARh4ASR8ASmAAR2EASAwCAQ0dAQ4gAQ8hARAiARIkARMmChQnCxUpARYrChcsDBotARsuARwvCiAyDSEzESI0AiM1AiQ2AiU3AiY4Aic6Aig8Cik9Eio_AitBCixCEy1DAi5EAi9FCjBIFDFJGDJKAzNLAzRMAzVNAzZOAzdQAzhSCjlTGTpVAztXCjxYGj1ZAz5aAz9bCkBeG0FfH0JhIENiIERlIEVmIEZnIEdpIEhrCklsIUpuIEtwCkxxIk1yIE5zIE90ClB3I1F4J1J5BFN6BFR7BFV8BFZ9BFd_BFiBAQpZggEoWoQBBFuGAQpchwEpXYgBBF6JAQRfigEKYo0BKmOOATBkkAEIZZEBCGaTAQhnlAEIaJUBCGmXAQhqmQEKa5oBMWycAQhtngEKbp8BMm-gAQhwoQEIcaIBCnKlATNzpgE5dKcBBnWoAQZ2qQEGd6oBBnirAQZ5rQEGeq8BCnuwATp8sgEGfbQBCn61ATt_tgEGgAG3AQaBAbgBCoIBuwE8gwG8AUKEAb4BBYUBvwEFhgHCAQWHAcMBBYgBxAEFiQHGAQWKAcgBCosByQFDjAHLAQWNAc0BCo4BzgFEjwHPAQWQAdABBZEB0QEKkgHUAUWTAdUBSw"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/enums.ts
var Role = {
  ADMIN: "ADMIN",
  GUEST: "GUEST",
  MANAGER: "MANAGER"
};
var RoomStatus = {
  AVAILABLE: "AVAILABLE",
  MAINTENANCE: "MAINTENANCE"
};
var BookingStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  CHECKED_IN: "CHECKED_IN",
  CHECKED_OUT: "CHECKED_OUT"
};
var PaymentStatus = {
  UNPAID: "UNPAID",
  PAID: "PAID",
  REFUNDED: "REFUNDED",
  FAILED: "FAILED"
};

// src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
import { bearer } from "better-auth/plugins";
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etc
  }),
  trustedOrigins: ["https://boshonto-totel-management-frontend.vercel.app", "http://localhost:3000"],
  emailAndPassword: {
    enabled: true
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: true,
        defaultValue: Role.GUEST
      },
      isDeleted: {
        type: "boolean",
        required: true,
        defaultValue: false
      },
      deletedAt: {
        type: "date",
        required: false,
        defaultValue: null
      }
    }
  },
  plugins: [
    bearer()
  ],
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60
      // 5 minutes
    }
  },
  advanced: {
    cookiePrefix: "better-auth",
    useSecureCookies: process.env.NODE_ENV === "production",
    crossSubDomainCookies: {
      enabled: false
    },
    disableCSRFCheck: true
    // Allow requests without Origin header (Postman, mobile apps, etc.)
  }
});

// src/middleware/AppError.ts
var AppError = class extends Error {
  statusCode;
  constructor(statusCode = 500, message) {
    super(message);
    this.statusCode = statusCode;
  }
};

// src/modules/auth/auth.service.ts
var createUser = async (payload) => {
  const { name, email, password } = payload;
  const existingUser = await prisma.user.findUnique({
    where: { email }
  });
  if (existingUser) {
    throw new AppError(status.CONFLICT, "User with this email already exists");
  }
  const data = await auth.api.signUpEmail({
    body: {
      name,
      email,
      password
    }
  });
  return data;
};
var loginUser = async (payload) => {
  const { email, password } = payload;
  const data = await auth.api.signInEmail({
    body: {
      email,
      password
    }
  });
  return data;
};
var logoutUser = async (req) => {
  if (req.headers) {
    throw new AppError(status.BAD_REQUEST, "Missing authentication headers");
  }
  const data = await auth.api.signOut({
    headers: req.headers
  });
  return data;
};
var getAllUsers = async () => {
  const users = await prisma.user.findMany();
  return users;
};
var getUserById = async (userId) => {
  const user = await prisma.user.findUnique({
    where: { id: userId }
  });
  return user;
};
var deleteUser = async (userId) => {
  const user = await prisma.user.findUnique({
    where: { id: userId }
  });
  if (!user) {
    throw new AppError(status.NOT_FOUND, "User not found");
  }
  const isCurrentlyDeleted = user.isDeleted;
  const updatedUser = await prisma.user.update({
    where: { id: userId },
    data: {
      isDeleted: !isCurrentlyDeleted,
      deletedAt: !isCurrentlyDeleted ? /* @__PURE__ */ new Date() : null
    }
  });
  return updatedUser;
};
var updateUserRole = async (id, role) => {
  const existingUser = await prisma.user.findUnique({
    where: { id }
  });
  if (!existingUser) {
    throw new AppError(status.NOT_FOUND, "User not found");
  }
  const updatedUser = await prisma.user.update({
    where: { id },
    data: role
  });
  return updatedUser;
};
var authServices = {
  createUser,
  loginUser,
  getAllUsers,
  deleteUser,
  logoutUser,
  updateUserRole,
  getUserById
};

// src/utils/shared/catchAsync.ts
var catchAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      next(error);
    }
  };
};
var catchAsync_default = catchAsync;

// src/utils/shared/sendResponse.ts
var sendResponse = (res, statusCode, message, data) => {
  res.status(statusCode).json({
    success: true,
    message,
    data
  });
};
var sendResponse_default = sendResponse;

// src/modules/auth/auth.contorller.ts
import status2 from "http-status";
var registerUser = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const data = await authServices.createUser(payload);
  sendResponse_default(res, status2.OK, "User registered successfully", data);
});
var loginUser2 = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const data = await authServices.loginUser(payload);
  sendResponse_default(res, status2.OK, "User logged in successfully", data);
});
var getAllUsersController = catchAsync_default(async (req, res) => {
  const data = await authServices.getAllUsers();
  sendResponse_default(res, status2.OK, "Users retrieved successfully", data);
});
var getUserByIdController = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const data = await authServices.getUserById(id);
  sendResponse_default(res, status2.OK, "User retrieved successfully", data);
});
var deleteUserController = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const data = await authServices.deleteUser(id);
  const message = data.isDeleted ? "User deleted successfully" : "User restored successfully";
  sendResponse_default(res, status2.OK, message, data);
});
var logoutUser2 = catchAsync_default(async (req, res) => {
  const data = await authServices.logoutUser(req);
  sendResponse_default(res, status2.OK, "User logged out successfully", data);
});
var updateUserRole2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const roleBody = req.body;
  const data = await authServices.updateUserRole(id, roleBody);
  sendResponse_default(res, status2.OK, "User role updated successfully", data);
});
var authController = {
  registerUser,
  loginUser: loginUser2,
  getAllUsersController,
  deleteUserController,
  logoutUser: logoutUser2,
  updateUserRole: updateUserRole2,
  getUserByIdController
};

// src/middleware/zodValidate.ts
var validateRequest = (schema) => {
  return (req, res, next) => {
    if (req.body.data) {
      req.body = JSON.parse(req.body.data);
    }
    const result = schema.safeParse(req.body);
    if (!result.success) {
      next(result.error);
    }
    req.body = result.data;
    next();
  };
};
var zodValidate_default = validateRequest;

// src/modules/auth/auth.validator.ts
import { z } from "zod";
var loginValidationSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1, { message: "Password is required" }).min(6, { message: "Password must be at least 6 characters long" })
});
var updateRoleValidationSchema = z.object({
  role: z.enum([Role.ADMIN, Role.GUEST, Role.MANAGER])
});

// src/middleware/checkAuth.ts
import status3 from "http-status";
var checkAuth = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(status3.UNAUTHORIZED).json({
          success: false,
          message: "Unauthorized access"
        });
      }
      req.user = {
        id: session.user.id,
        name: session.user.name,
        email: session.user.email,
        isdeleted: session.user.isDeleted,
        role: session.user.role
      };
      if (roles.length > 0 && !roles.includes(req.user.role)) {
        return res.status(status3.FORBIDDEN).json({
          success: false,
          message: "You do not have permission to access this resource"
        });
      }
      next();
    } catch (error) {
      return res.status(status3.UNAUTHORIZED).json({
        success: false,
        message: "Authentication failed"
      });
    }
  };
};

// src/modules/auth/auth.router.ts
var router = Router();
router.post("/register", authController.registerUser);
router.post("/login", zodValidate_default(loginValidationSchema), authController.loginUser);
router.get("/users", checkAuth(Role.ADMIN), authController.getAllUsersController);
router.get("/user/:id", checkAuth(Role.ADMIN), authController.getUserByIdController);
router.patch("/delete-restore/:id", checkAuth(Role.ADMIN), authController.deleteUserController);
router.patch("/update-role/:id", checkAuth(Role.ADMIN), zodValidate_default(updateRoleValidationSchema), authController.updateUserRole);
router.post("/logout", checkAuth(), authController.logoutUser);
var authRoter = router;

// src/modules/manager/manager.route.ts
import { Router as Router2 } from "express";

// src/modules/manager/manager.controller.ts
import status5 from "http-status";

// src/modules/manager/manager.services.ts
import status4 from "http-status";
var createManager = async (payload) => {
  const { name, email, password } = payload;
  const existingUser = await prisma.user.findUnique({
    where: { email }
  });
  if (existingUser) {
    throw new AppError(status4.CONFLICT, "User with this email already exists");
  }
  const data = await auth.api.signUpEmail({
    body: {
      name,
      email,
      password,
      role: Role.MANAGER
    }
  });
  return data;
};
var managerServices = {
  createManager
};

// src/modules/manager/manager.controller.ts
var createManager2 = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const data = await managerServices.createManager(payload);
  sendResponse_default(res, status5.CREATED, "Manager created successfully", data);
});
var managerController = {
  createManager: createManager2
};

// src/modules/manager/manager.validator.ts
import { z as z2 } from "zod";
var createManagerSchema = z2.object({
  name: z2.string().min(1, { message: "Name is required" }),
  email: z2.string().email({ message: "Invalid email address" }),
  password: z2.string().min(6, { message: "Password must be at least 6 characters long" })
});

// src/modules/manager/manager.route.ts
var router2 = Router2();
router2.post(
  "/register-manager",
  checkAuth(Role.ADMIN),
  zodValidate_default(createManagerSchema),
  managerController.createManager
);
var managerRouter = router2;

// src/modules/room/room.route.ts
import { Router as Router3 } from "express";

// src/modules/room/room.controller.ts
import status7 from "http-status";

// src/modules/room/room.services.ts
import status6 from "http-status";
var createRoom = async (payload) => {
  const { roomNumber, roomType, title, description, pricePerNight, capacity, bedType, images, floor } = payload;
  const existingRoom = await prisma.room.findUnique({
    where: { roomNumber }
  });
  if (existingRoom) {
    throw new AppError(status6.CONFLICT, "Room with this room number already exists");
  }
  const room = await prisma.room.create({
    data: {
      roomNumber,
      roomType,
      title,
      description,
      pricePerNight,
      capacity,
      bedType,
      images,
      floor
    }
  });
  return room;
};
var getAllRooms = async () => {
  const rooms = await prisma.room.findMany();
  return rooms;
};
var getRoomById = async (id) => {
  const room = await prisma.room.findUnique({
    where: { id }
  });
  if (!room) {
    throw new AppError(status6.NOT_FOUND, "Room not found");
  }
  return room;
};
var deleteRoom = async (id) => {
  const room = await prisma.room.findUnique({
    where: { id }
  });
  if (!room) {
    throw new AppError(status6.NOT_FOUND, "Room not found");
  }
  if (room.status === RoomStatus.BOOKED) {
    throw new AppError(status6.FORBIDDEN, "This room is currently booked and cannot be deleted");
  }
  const deletedRoom = await prisma.room.delete({
    where: { id }
  });
  return deletedRoom;
};
var updateRoom = async (id, payload) => {
  const room = await prisma.room.findUnique({
    where: { id }
  });
  if (!room) {
    throw new AppError(status6.NOT_FOUND, "Room not found");
  }
  if (payload.roomNumber && payload.roomNumber !== room.roomNumber) {
    const existingRoom = await prisma.room.findUnique({
      where: { roomNumber: payload.roomNumber }
    });
    if (existingRoom) {
      throw new AppError(status6.CONFLICT, "Room with this room number already exists");
    }
  }
  const updatedRoom = await prisma.room.update({
    where: { id },
    data: payload
  });
  return updatedRoom;
};
var roomServices = {
  createRoom,
  getAllRooms,
  getRoomById,
  deleteRoom,
  updateRoom
};

// src/modules/room/room.controller.ts
var createRoom2 = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const data = await roomServices.createRoom(payload);
  sendResponse_default(res, status7.CREATED, "Room created successfully", data);
});
var getAllRooms2 = catchAsync_default(async (req, res) => {
  const data = await roomServices.getAllRooms();
  sendResponse_default(res, status7.OK, "Rooms retrieved successfully", data);
});
var getRoomById2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const data = await roomServices.getRoomById(id);
  sendResponse_default(res, status7.OK, "Room retrieved successfully", data);
});
var deleteRoom2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const data = await roomServices.deleteRoom(id);
  sendResponse_default(res, status7.OK, "Room deleted successfully", data);
});
var updateRoom2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const payload = req.body;
  const data = await roomServices.updateRoom(id, payload);
  sendResponse_default(res, status7.OK, "Room updated successfully", data);
});
var roomController = {
  createRoom: createRoom2,
  getAllRooms: getAllRooms2,
  getRoomById: getRoomById2,
  deleteRoom: deleteRoom2,
  updateRoom: updateRoom2
};

// src/modules/room/room.validator.ts
import { z as z3 } from "zod";
var createRoomSchema = z3.object({
  roomNumber: z3.string().min(1, { message: "Room number is required" }),
  roomType: z3.enum(["SINGLE", "DOUBLE", "DELUXE", "SUITE", "FAMILY"], {
    message: "Invalid room type"
  }),
  title: z3.string().min(1, { message: "Title is required" }),
  description: z3.string().optional(),
  pricePerNight: z3.number().positive({ message: "Price per night must be positive" }),
  capacity: z3.number().int().positive({ message: "Capacity must be a positive integer" }),
  bedType: z3.enum(["SINGLE", "DOUBLE", "QUEEN", "KING"], {
    message: "Invalid bed type"
  }),
  images: z3.string().optional(),
  floor: z3.number().int().min(0).optional()
});
var updateRoomSchema = z3.object({
  roomNumber: z3.string().min(1, { message: "Room number is required" }).optional(),
  roomType: z3.enum(["SINGLE", "DOUBLE", "DELUXE", "SUITE", "FAMILY"], {
    message: "Invalid room type"
  }).optional(),
  title: z3.string().min(1, { message: "Title is required" }).optional(),
  description: z3.string().optional(),
  pricePerNight: z3.number().positive({ message: "Price per night must be positive" }).optional(),
  capacity: z3.number().int().positive({ message: "Capacity must be a positive integer" }).optional(),
  bedType: z3.enum(["SINGLE", "DOUBLE", "QUEEN", "KING"], {
    message: "Invalid bed type"
  }).optional(),
  images: z3.string().min(1, { message: "Images are required" }).optional(),
  status: z3.enum(["AVAILABLE", "BOOKED", "MAINTENANCE"], {
    message: "Invalid room status"
  }).optional(),
  floor: z3.number().int().min(0).optional()
});

// src/generated/prisma/internal/prismaNamespaceBrowser.ts
import * as runtime3 from "@prisma/client/runtime/index-browser";
var NullTypes4 = {
  DbNull: runtime3.NullTypes.DbNull,
  JsonNull: runtime3.NullTypes.JsonNull,
  AnyNull: runtime3.NullTypes.AnyNull
};
var TransactionIsolationLevel2 = runtime3.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});

// src/modules/room/room.route.ts
var router3 = Router3();
router3.post(
  "/create-room",
  checkAuth(Role.ADMIN, Role.MANAGER),
  zodValidate_default(createRoomSchema),
  roomController.createRoom
);
router3.get(
  "/get-all-rooms",
  roomController.getAllRooms
);
router3.get(
  "/get-room/:id",
  roomController.getRoomById
);
router3.delete(
  "/delete-room/:id",
  checkAuth(Role.ADMIN, Role.MANAGER),
  roomController.deleteRoom
);
router3.patch(
  "/update-room/:id",
  checkAuth(Role.ADMIN, Role.MANAGER),
  zodValidate_default(updateRoomSchema),
  roomController.updateRoom
);
var roomRouter = router3;

// src/modules/booking/booking.route.ts
import { Router as Router4 } from "express";

// src/modules/booking/booking.controller.ts
import status9 from "http-status";

// src/modules/booking/booking.services.ts
import status8 from "http-status";
import { Decimal as Decimal3 } from "@prisma/client/runtime/client";

// src/config/stripe.ts
import Stripe from "stripe";

// src/config/env.ts
var loadEnv = () => {
  const envList = [
    "PORT",
    "STRIPE_WEBHOOK_SECRET",
    "STRIPE_SECRET_KEY",
    "BETTER_AUTH_URL",
    "BETTER_AUTH_SECRET",
    "NODE_ENV",
    "DATABASE_URL",
    "PROD_APP_URL",
    "APP_URL",
    "FRONTEND_URL"
  ];
  envList.forEach((env) => {
    if (!process.env[env]) {
      throw new Error(`Missing environment variable: ${env}`);
    }
  });
  return {
    PORT: process.env.PORT,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    PROD_APP_URL: process.env.PROD_APP_URL,
    APP_URL: process.env.APP_URL,
    FRONTEND_URL: process.env.FRONTEND_URL
  };
};
var envVar = loadEnv();

// src/config/stripe.ts
var stripe = new Stripe(envVar.STRIPE_SECRET_KEY);

// src/modules/booking/booking.services.ts
import { v7 as uuidv7 } from "uuid";
var createBooking = async (payload, userId) => {
  const { roomId, checkInDate, checkOutDate, specialRequest } = payload;
  const today = /* @__PURE__ */ new Date();
  today.setUTCHours(0, 0, 0, 0);
  const checkIn = /* @__PURE__ */ new Date(checkInDate + "T00:00:00Z");
  const checkOut = /* @__PURE__ */ new Date(checkOutDate + "T00:00:00Z");
  if (checkIn < today || checkOut < today) {
    throw new AppError(status8.BAD_REQUEST, "Booking dates cannot be in the past");
  }
  if (checkIn >= checkOut) {
    throw new AppError(status8.BAD_REQUEST, "Check-out date must be after check-in date");
  }
  const totalNights = Math.ceil(
    (checkOut.getTime() - checkIn.getTime()) / (1e3 * 60 * 60 * 24)
  );
  const result = await prisma.$transaction(async (tx) => {
    const room = await tx.room.findUnique({
      where: { id: roomId }
    });
    if (!room) {
      throw new AppError(status8.NOT_FOUND, "Room not found");
    }
    const conflictingBooking = await tx.booking.findFirst({
      where: {
        roomId,
        OR: [
          {
            AND: [
              { checkInDate: { lte: checkIn } },
              { checkOutDate: { gt: checkIn } }
            ]
          },
          {
            AND: [
              { checkInDate: { lt: checkOut } },
              { checkOutDate: { gte: checkOut } }
            ]
          },
          {
            AND: [
              { checkInDate: { gte: checkIn } },
              { checkOutDate: { lte: checkOut } }
            ]
          }
        ],
        bookingStatus: {
          in: [BookingStatus.PENDING, BookingStatus.CHECKED_IN, BookingStatus.CONFIRMED]
        }
      }
    });
    if (conflictingBooking) {
      throw new AppError(status8.CONFLICT, "Room is already booked for the selected dates");
    }
    const totalPrice = Number(room.pricePerNight) * totalNights;
    const booking = await tx.booking.create({
      data: {
        userId,
        roomId,
        checkInDate: checkIn,
        checkOutDate: checkOut,
        totalNights,
        totalPrice,
        specialRequest
      },
      include: {
        user: { select: { id: true, name: true, email: true } },
        room: { select: { id: true, roomNumber: true, title: true, pricePerNight: true } }
      }
    });
    const transactionId = String(uuidv7());
    const payment = await tx.payment.create({
      data: {
        bookingId: booking.id,
        amount: totalPrice,
        transactionId
      }
    });
    return { booking, payment, room };
  });
  console.log("booking_id", result.booking.id);
  let session;
  try {
    session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      mode: "payment",
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: `Room booking: ${result.room.title}`
            },
            // ✅ Decimal fix
            unit_amount: Number(result.room.pricePerNight) * 100
          },
          // ✅ প্রতি রাতের জন্য quantity
          quantity: totalNights
        }
      ],
      metadata: {
        bookingId: result.booking.id,
        paymentId: result.payment.id
      },
      success_url: `${envVar.FRONTEND_URL}/create-booking/success`,
      cancel_url: `${envVar.FRONTEND_URL}/create-booking/cancel`
    });
  } catch (error) {
    await prisma.payment.update({
      where: { id: result.payment.id },
      data: { status: PaymentStatus.FAILED }
    });
    throw new AppError(
      status8.INTERNAL_SERVER_ERROR,
      "Payment gateway error, please try again"
    );
  }
  if (!session.url) {
    await prisma.payment.update({
      where: { id: result.payment.id },
      data: { status: PaymentStatus.FAILED }
    });
    throw new AppError(
      status8.INTERNAL_SERVER_ERROR,
      "Payment session creation failed"
    );
  }
  return {
    booking: result.booking,
    payment: result.payment,
    paymentUrl: session.url
  };
};
var getAllBookings = async () => {
  const bookings = await prisma.booking.findMany({
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          roomNumber: true,
          title: true,
          pricePerNight: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return bookings;
};
var getBookingById = async (bookingId) => {
  const booking = await prisma.booking.findUnique({
    where: { id: bookingId },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          roomNumber: true,
          title: true,
          pricePerNight: true
        }
      }
    }
  });
  if (!booking) {
    throw new AppError(status8.NOT_FOUND, "Booking not found");
  }
  return booking;
};
var getBookingsByUserIdAndEmail = async (userId, userEmail) => {
  const bookings = await prisma.booking.findMany({
    where: {
      userId,
      user: {
        email: userEmail
      }
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          roomNumber: true,
          title: true,
          pricePerNight: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return bookings;
};
var updateBooking = async (bookingId, payload, userId) => {
  const existingBooking = await prisma.booking.findUnique({
    where: { id: bookingId },
    include: {
      room: true
    }
  });
  if (!existingBooking) {
    throw new AppError(status8.NOT_FOUND, "Booking not found");
  }
  if (existingBooking.userId !== userId) {
    throw new AppError(status8.FORBIDDEN, "You can only update your own bookings");
  }
  if (existingBooking.bookingStatus !== BookingStatus.PENDING) {
    throw new AppError(status8.BAD_REQUEST, "Only PENDING bookings can be updated");
  }
  const { checkInDate, checkOutDate, specialRequest } = payload;
  const newCheckIn = checkInDate ? /* @__PURE__ */ new Date(checkInDate + "T00:00:00Z") : existingBooking.checkInDate;
  const newCheckOut = checkOutDate ? /* @__PURE__ */ new Date(checkOutDate + "T00:00:00Z") : existingBooking.checkOutDate;
  if (checkInDate || checkOutDate) {
    const today = /* @__PURE__ */ new Date();
    if (newCheckIn < today || newCheckOut < today) {
      throw new AppError(status8.BAD_REQUEST, "Booking dates cannot be in the past");
    }
    if (newCheckIn >= newCheckOut) {
      throw new AppError(status8.BAD_REQUEST, "Check-out date must be after check-in date");
    }
    const conflictingBooking = await prisma.booking.findFirst({
      where: {
        roomId: existingBooking.roomId,
        id: { not: bookingId },
        // Exclude current booking
        OR: [
          {
            AND: [
              { checkInDate: { lte: newCheckIn } },
              { checkOutDate: { gt: newCheckIn } }
            ]
          },
          {
            AND: [
              { checkInDate: { lt: newCheckOut } },
              { checkOutDate: { gte: newCheckOut } }
            ]
          },
          {
            AND: [
              { checkInDate: { gte: newCheckIn } },
              { checkOutDate: { lte: newCheckOut } }
            ]
          }
        ],
        bookingStatus: {
          in: [BookingStatus.PENDING]
        }
      }
    });
    if (conflictingBooking) {
      throw new AppError(status8.CONFLICT, "Room is already booked for the selected dates");
    }
  }
  let totalNights = existingBooking.totalNights;
  let totalPrice = existingBooking.totalPrice;
  if (checkInDate || checkOutDate) {
    totalNights = Math.ceil(
      (newCheckOut.getTime() - newCheckIn.getTime()) / (1e3 * 60 * 60 * 24)
    );
    totalPrice = new Decimal3(existingBooking.room.pricePerNight).mul(totalNights);
  }
  const updatedBooking = await prisma.booking.update({
    where: { id: bookingId },
    data: {
      checkInDate: checkInDate ? newCheckIn : void 0,
      checkOutDate: checkOutDate ? newCheckOut : void 0,
      totalNights,
      totalPrice,
      specialRequest: specialRequest !== void 0 ? specialRequest : void 0
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          roomNumber: true,
          title: true,
          pricePerNight: true
        }
      }
    }
  });
  return updatedBooking;
};
var updateBookingStatus = async (bookingId, payload, userId, userRole) => {
  const { bookingStatus } = payload;
  const existingBooking = await prisma.booking.findUnique({
    where: { id: bookingId },
    include: {
      user: { select: { id: true, name: true, email: true } },
      room: { select: { id: true, roomNumber: true, title: true, pricePerNight: true } }
    }
  });
  if (!existingBooking) {
    throw new AppError(status8.NOT_FOUND, "Booking not found");
  }
  if (userRole === Role.GUEST) {
    if (existingBooking.userId !== userId) {
      throw new AppError(status8.FORBIDDEN, "You can only update your own bookings");
    }
    if (bookingStatus !== BookingStatus.CANCELLED) {
      throw new AppError(status8.FORBIDDEN, "Guests can only cancel bookings");
    }
    if (existingBooking.bookingStatus !== BookingStatus.PENDING) {
      throw new AppError(status8.BAD_REQUEST, "Only PENDING bookings can be cancelled by guests");
    }
  }
  const roomStatusMap = {
    [BookingStatus.CANCELLED]: RoomStatus.AVAILABLE,
    [BookingStatus.CHECKED_OUT]: RoomStatus.AVAILABLE
  };
  const newRoomStatus = roomStatusMap[bookingStatus];
  const updatedBooking = await prisma.$transaction(async (tx) => {
    const booking = await tx.booking.update({
      where: { id: bookingId },
      data: { bookingStatus },
      include: {
        user: { select: { id: true, name: true, email: true } },
        room: { select: { id: true, roomNumber: true, title: true, pricePerNight: true } }
      }
    });
    if (newRoomStatus) {
      await tx.room.update({
        where: { id: existingBooking.roomId },
        data: { status: newRoomStatus }
      });
    }
    return booking;
  });
  return updatedBooking;
};
var bookingService = {
  createBooking,
  getAllBookings,
  getBookingById,
  getBookingsByUserIdAndEmail,
  updateBooking,
  updateBookingStatus
};

// src/modules/booking/booking.controller.ts
var createBookingController = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const userId = req?.user?.id;
  const data = await bookingService.createBooking(payload, userId);
  sendResponse_default(res, status9.CREATED, "Booking created successfully", data);
});
var getAllBookingsController = catchAsync_default(async (req, res) => {
  const data = await bookingService.getAllBookings();
  sendResponse_default(res, status9.OK, "All bookings retrieved successfully", data);
});
var getBookingById2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const data = await bookingService.getBookingById(id);
  sendResponse_default(res, status9.OK, "Booking retrieved successfully", data);
});
var getMyBookings = catchAsync_default(async (req, res) => {
  const userId = req?.user?.id;
  const userEmail = req?.user?.email;
  const data = await bookingService.getBookingsByUserIdAndEmail(userId, userEmail);
  sendResponse_default(res, status9.OK, "User bookings retrieved successfully", data);
});
var updateBooking2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const payload = req.body;
  const userId = req?.user?.id;
  const data = await bookingService.updateBooking(id, payload, userId);
  sendResponse_default(res, status9.OK, "Booking updated successfully", data);
});
var updateBookingStatus2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const payload = req.body;
  const userId = req?.user?.id;
  const userRole = req?.user?.role;
  if (!userRole) {
    throw new AppError(status9.UNAUTHORIZED, "Unauthorized");
  }
  const data = await bookingService.updateBookingStatus(id, payload, userId, userRole);
  sendResponse_default(res, status9.OK, "Booking status updated successfully", data);
});
var bookingController = {
  createBookingController,
  getAllBookingsController,
  getBookingById: getBookingById2,
  getMyBookings,
  updateBooking: updateBooking2,
  updateBookingStatus: updateBookingStatus2
};

// src/modules/booking/booking.validator.ts
import { z as z4 } from "zod";
var createBookingValidationSchema = z4.object({
  roomId: z4.string().min(1, "Room ID is required"),
  checkInDate: z4.string().refine((date) => !isNaN(Date.parse(date)), {
    message: "Invalid check-in date format"
  }),
  checkOutDate: z4.string().refine((date) => !isNaN(Date.parse(date)), {
    message: "Invalid check-out date format"
  }),
  specialRequest: z4.string().optional()
}).refine((data) => {
  const checkIn = new Date(data.checkInDate);
  const checkOut = new Date(data.checkOutDate);
  return checkOut > checkIn;
}, {
  message: "Check-out date must be after check-in date",
  path: ["checkOutDate"]
});
var updateBookingValidationSchema = z4.object({
  checkInDate: z4.string().refine((date) => !isNaN(Date.parse(date)), {
    message: "Invalid check-in date format"
  }).optional(),
  checkOutDate: z4.string().refine((date) => !isNaN(Date.parse(date)), {
    message: "Invalid check-out date format"
  }).optional(),
  specialRequest: z4.string().optional()
}).refine((data) => {
  if (data.checkInDate && data.checkOutDate) {
    const checkIn = new Date(data.checkInDate);
    const checkOut = new Date(data.checkOutDate);
    return checkOut > checkIn;
  }
  return true;
}, {
  message: "Check-out date must be after check-in date",
  path: ["checkOutDate"]
});
var updateBookingStatusValidationSchema = z4.object({
  bookingStatus: z4.enum(["PENDING", "CONFIRMED", "CANCELLED", "CHECKED_IN", "CHECKED_OUT"], {
    message: "Invalid booking status"
    // ✅ errorMap → message
  })
});

// src/modules/booking/booking.route.ts
var router4 = Router4();
router4.post(
  "/room",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  zodValidate_default(createBookingValidationSchema),
  bookingController.createBookingController
);
router4.get(
  "/all",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  bookingController.getAllBookingsController
);
router4.get(
  "/my-bookings",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  bookingController.getMyBookings
);
router4.patch(
  "/update/:id",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  zodValidate_default(updateBookingValidationSchema),
  bookingController.updateBooking
);
router4.patch(
  "/status/:id",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  zodValidate_default(updateBookingStatusValidationSchema),
  bookingController.updateBookingStatus
);
router4.get(
  "/:id",
  checkAuth(Role.GUEST, Role.ADMIN, Role.MANAGER),
  bookingController.getBookingById
);
var bookingRouter = router4;

// src/modules/review/review.router.ts
import { Router as Router5 } from "express";

// src/modules/review/review.serices.ts
import status10 from "http-status";
var createReview = async (payload, userId) => {
  const { roomId, rating, comment } = payload;
  const ratingNum = Number(rating);
  if (ratingNum < 1 || ratingNum > 5) {
    throw new AppError(status10.BAD_REQUEST, "Rating must be between 1 and 5");
  }
  const room = await prisma.room.findUnique({
    where: { id: roomId }
  });
  if (!room) {
    throw new AppError(status10.NOT_FOUND, "Room not found");
  }
  const booking = await prisma.booking.findFirst({
    where: {
      userId,
      roomId,
      bookingStatus: BookingStatus.CHECKED_OUT
    }
  });
  if (!booking) {
    throw new AppError(status10.FORBIDDEN, "You can only review rooms you've checked out from");
  }
  const existingReview = await prisma.review.findFirst({
    where: {
      userId,
      roomId
    }
  });
  if (existingReview) {
    throw new AppError(status10.CONFLICT, "You have already reviewed this room");
  }
  const review = await prisma.review.create({
    data: {
      userId,
      roomId,
      rating: ratingNum,
      comment
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          title: true
        }
      }
    }
  });
  return review;
};
var getAllReviews = async () => {
  const reviews = await prisma.review.findMany({
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      room: {
        select: {
          id: true,
          title: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return reviews;
};
var getReviewsByRoom = async (roomId) => {
  const reviews = await prisma.review.findMany({
    where: { roomId },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return reviews;
};
var getReviewsByUser = async (userId) => {
  const reviews = await prisma.review.findMany({
    where: { userId },
    include: {
      room: {
        select: {
          id: true,
          title: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return reviews;
};
var deleteReview = async (reviewId, userId) => {
  const review = await prisma.review.findFirst({
    where: {
      id: reviewId,
      userId
    }
  });
  if (!review) {
    throw new AppError(status10.NOT_FOUND, "Review not found or you don't have permission to delete it");
  }
  await prisma.review.delete({
    where: { id: reviewId }
  });
  return { message: "Review deleted successfully" };
};
var reviewServices = {
  createReview,
  getAllReviews,
  getReviewsByRoom,
  getReviewsByUser,
  deleteReview
};

// src/modules/review/review.controller.ts
import status11 from "http-status";
var createReview2 = catchAsync_default(async (req, res) => {
  const payload = req.body;
  const userId = req.user.id;
  const data = await reviewServices.createReview(payload, userId);
  sendResponse_default(res, status11.CREATED, "Review created successfully", data);
});
var getAllReviews2 = catchAsync_default(async (req, res) => {
  const data = await reviewServices.getAllReviews();
  sendResponse_default(res, status11.OK, "Reviews retrieved successfully", data);
});
var getReviewsByRoom2 = catchAsync_default(async (req, res) => {
  const { roomId } = req.params;
  const data = await reviewServices.getReviewsByRoom(roomId);
  sendResponse_default(res, status11.OK, "Reviews retrieved successfully", data);
});
var getReviewsByUser2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const data = await reviewServices.getReviewsByUser(userId);
  sendResponse_default(res, status11.OK, "Your reviews retrieved successfully", data);
});
var deleteReview2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;
  const data = await reviewServices.deleteReview(id, userId);
  sendResponse_default(res, status11.OK, data.message, null);
});
var reviewController = {
  createReview: createReview2,
  getAllReviews: getAllReviews2,
  getReviewsByRoom: getReviewsByRoom2,
  getReviewsByUser: getReviewsByUser2,
  deleteReview: deleteReview2
};

// src/modules/review/review.validator.ts
import { z as z5 } from "zod";
var createReviewValidationSchema = z5.object({
  roomId: z5.string().min(1, "Room ID is required"),
  rating: z5.union([z5.number(), z5.string()]),
  comment: z5.string().optional()
});

// src/modules/review/review.router.ts
var router5 = Router5();
router5.post("/create", checkAuth(Role.ADMIN, Role.GUEST, Role.MANAGER), zodValidate_default(createReviewValidationSchema), reviewController.createReview);
router5.get("/all", checkAuth(Role.ADMIN), reviewController.getAllReviews);
router5.get("/room/:roomId", reviewController.getReviewsByRoom);
router5.get("/my-reviews", checkAuth(), reviewController.getReviewsByUser);
router5.delete("/:id", checkAuth(), reviewController.deleteReview);
var reviewRouter = router5;

// src/router/index.ts
var router6 = Router6();
router6.use("/auth", authRoter);
router6.use("/manager", managerRouter);
router6.use("/room", roomRouter);
router6.use("/booking", bookingRouter);
router6.use("/review", reviewRouter);
var router_default = router6;

// src/middleware/notFound.ts
import status12 from "http-status";
var notFound = (req, res) => {
  res.status(status12.NOT_FOUND).json({
    success: false,
    message: `Route ${req.originalUrl} Not Found`
  });
};

// src/middleware/globalErrorHandler.ts
import { ZodError } from "zod";
import status13 from "http-status";
import { PrismaClientKnownRequestError as PrismaClientKnownRequestError2, PrismaClientValidationError as PrismaClientValidationError2 } from "@prisma/client/runtime/client";
var globalErrorHandler = (err, req, res, next) => {
  if (process.env.NODE_ENV === "development") {
    console.log(err);
  }
  let statusCode = status13.INTERNAL_SERVER_ERROR;
  let message = err.message || "Internal Server Error";
  let errorSources = [];
  let stack;
  if (err instanceof ZodError) {
    statusCode = status13.UNPROCESSABLE_ENTITY;
    message = "Validation failed";
    errorSources = err.issues.map((issue) => ({
      path: issue.path.join("=>"),
      message: issue.message
    }));
    stack = err.stack;
  } else if (err instanceof PrismaClientKnownRequestError2) {
    stack = err.stack;
    if (err.code === "P2002") {
      statusCode = status13.CONFLICT;
      message = "Duplicate entry found";
      errorSources = [{
        path: err.meta?.target?.join(", ") || "",
        message: `${err.meta?.target?.join(", ")} already exists`
      }];
    } else if (err.code === "P2025") {
      statusCode = status13.NOT_FOUND;
      message = "Record not found";
      errorSources = [{
        path: "",
        message: err.meta?.cause || "Requested record does not exist"
      }];
    } else if (err.code === "P2003") {
      statusCode = status13.BAD_REQUEST;
      message = "Invalid reference";
      errorSources = [{
        path: err.meta?.field_name || "",
        message: "Related record does not exist"
      }];
    } else {
      statusCode = status13.BAD_REQUEST;
      message = "Database error occurred";
      errorSources = [{ path: "", message: err.message }];
    }
  } else if (err instanceof PrismaClientValidationError2) {
    statusCode = status13.BAD_REQUEST;
    message = "Prisma validation error";
    errorSources = [{ path: "", message: err.message }];
    stack = err.stack;
  } else if (err instanceof AppError) {
    statusCode = err.statusCode;
    message = err.message;
    stack = err.stack;
    errorSources = [{ path: "", message: err.message }];
  } else if (err instanceof Error) {
    statusCode = status13.INTERNAL_SERVER_ERROR;
    message = err.message;
    stack = err.stack;
    errorSources = [{ path: "", message: err.message }];
  }
  res.status(statusCode).json({
    success: false,
    message,
    errorSources,
    error: process.env.NODE_ENV === "development" ? err : void 0,
    stack: process.env.NODE_ENV === "development" ? stack : void 0
  });
};

// src/app.ts
import { toNodeHandler } from "better-auth/node";

// src/modules/payment/payment.controller.ts
import status14 from "http-status";

// src/modules/payment/payment.services.ts
var handleStripeWebhookEvent = async (event) => {
  const isExistPayment = await prisma.payment.findFirst({
    where: {
      stripeEventId: event.id
    }
  });
  if (isExistPayment) {
    console.log(`event id ${event.id} is already processed`);
    return { message: `event id ${event.id} is already processed` };
  }
  switch (event.type) {
    case "checkout.session.completed": {
      const session = event.data.object;
      const bookingId = session.metadata?.bookingId;
      const paymentId = session.metadata?.paymentId;
      if (!bookingId || !paymentId) {
        console.log("Missing appointmentId or paymentId in session metadata");
        return { message: "Missing appointmentId or paymentId in session metadata" };
      }
      const booking = await prisma.booking.findFirst({
        where: {
          id: bookingId
        }
      });
      if (!booking) {
        console.error(`Appointment with id ${bookingId} not found`);
        return { message: `Appointment with id ${bookingId} not found` };
      }
      await prisma.$transaction(async (tx) => {
        await tx.booking.update({
          where: {
            id: bookingId
          },
          data: {
            paymentStatus: session.payment_status === "paid" ? PaymentStatus.PAID : PaymentStatus.UNPAID,
            bookingStatus: session.payment_status === "paid" ? BookingStatus.CONFIRMED : BookingStatus.PENDING
          }
        });
        await tx.payment.update({
          where: {
            id: paymentId
          },
          data: {
            stripeEventId: event.id,
            status: session.payment_status === "paid" ? PaymentStatus.PAID : PaymentStatus.UNPAID,
            paymentGatewayData: session
          }
        });
      });
      console.log(`Processed checkout.session.completed for booking ${booking} and payment ${paymentId}`);
      break;
    }
    case "checkout.session.expired": {
      const session = event.data.object;
      console.log(`Checkout session ${session.id} expired. Marking associated payment as failed.`);
      break;
    }
    case "payment_intent.payment_failed": {
      const session = event.data.object;
      console.log(`payment ${session.id} failed. Marking associated payment as failed.`);
      break;
    }
    default:
      console.log(`Unhandled event type ${event.type}`);
  }
  return { message: `Webhook Event ${event.id} processed successfully` };
};
var paymentServices = {
  handleStripeWebhookEvent
};

// src/modules/payment/payment.controller.ts
var handleStripeWebhooEvent = catchAsync_default(async (req, res) => {
  const singnature = req.headers["stripe-signature"];
  const secrate = envVar.STRIPE_WEBHOOK_SECRET;
  if (!singnature || !secrate) {
    console.error("Missing webhook secrate or singnature");
    return res.status(status14.BAD_REQUEST).json({ message: "Missing webhook secrate or singnature" });
  }
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, singnature, secrate);
  } catch (error) {
    console.error("proccessing stripe error", error);
    return res.status(status14.BAD_REQUEST).json({ message: "proccessing stripe error" });
  }
  try {
    const result = await paymentServices.handleStripeWebhookEvent(event);
    sendResponse_default(
      res,
      status14.OK,
      "Stripe webhook event processed successfully",
      result
    );
  } catch (error) {
    console.log("prisma error is occured");
    return res.status(status14.BAD_REQUEST).json({
      success: false,
      message: "Error handling Stripe webhook event",
      error
    });
  }
});
var paymentController = {
  handleStripeWebhooEvent
};

// src/app.ts
dotenv.config();
var app = express();
var allowedOrigins = [
  envVar.APP_URL || "http://localhost:3000",
  envVar.PROD_APP_URL
  // Production frontend URL
].filter(Boolean);
app.post(
  "/webhook",
  express.raw({ type: "application/json" }),
  paymentController.handleStripeWebhooEvent
);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/next-blog-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/v1", router_default);
app.get("/", (req, res) => {
  res.send("Hello, TypeScript + Express!");
});
app.use(globalErrorHandler);
app.use(notFound);

// src/index.ts
var index_default = app;
export {
  index_default as default
};
